{
  "Id": 50332557,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope AshCinder initializer init\r\n\t\r\n\tglobals\r\n\t\tpublic trigger Trigger = null\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == 'A0GI' and combat( GetSpellAbilityUnit(), true, 0 )\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local group g = CreateGroup()\r\n\t    local unit u\r\n\t    local integer cyclA = 1\r\n\t    local integer cyclAEnd \r\n\t    local unit caster\r\n\t    local real dmg\r\n\t    local effect anim\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        call textst( udg_string[0] + GetObjectName('A0GI'), caster, 64, 90, 10, 1.5 )\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t    endif\r\n\t    \r\n\t    set cyclAEnd =  eyest( caster )\r\n\t    set dmg = 125 + ( ( SetCount_GetPieces(caster, SET_MECH) - 1 ) * 125 )\r\n\t    set dmg = RMaxBJ(dmg, 125)\r\n\t    \r\n\t    set anim = AddSpecialEffect( \"Abilities\\\\Spells\\\\Orc\\\\WarStomp\\\\WarStompCaster.mdl\", GetUnitX( caster ), GetUnitY( caster ) )\r\n\t    call BlzSetSpecialEffectScale( anim, 5 )\r\n\t    call DestroyEffect( anim ) \r\n\t    loop\r\n\t        exitwhen cyclA > cyclAEnd\r\n\t        call GroupEnumUnitsInRange( g, GetUnitX( caster ), GetUnitY( caster ), 5000, null )\r\n\t        loop\r\n\t            set u = FirstOfGroup(g)\r\n\t            exitwhen u == null\r\n\t            if unitst( u, caster, \"enemy\" ) then\r\n\t                call UnitDamageTarget( caster, u, dmg, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n\t            endif\r\n\t            call GroupRemoveUnit(g,u)\r\n\t        endloop\r\n\t        set cyclA = cyclA + 1\r\n\t    endloop\r\n\t    \r\n\t    call DestroyGroup( g )\r\n\t    set g = null\r\n\t    set u = null\r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set Trigger = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( Trigger, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n\t    call TriggerAddCondition( Trigger, Condition( function condition ) )\r\n\t    call TriggerAddAction( Trigger, function action )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}