{
  "Id": 50332611,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope DeadlySpores initializer init\r\n\r\n\tglobals\r\n\t\tprivate unit Aura = null\r\n\t\tprivate integer Stacks = 0\r\n\t\t\r\n\t\tprivate constant real EXTRA_DAMAGE_PER_STACK = 0.4\r\n\t\tprivate constant integer STACK_LIMIT = 10\r\n\t\tprivate constant integer ABILITY_CAST = 'A02Q'\r\n\tendglobals\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_CAST and combat( GetSpellAbilityUnit(), true, ABILITY_CAST )\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local unit caster\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        call textst( udg_string[0] + GetObjectName(ABILITY_CAST), caster, 64, 90, 10, 1.5 )\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t    endif\r\n\t\tcall eyest( caster )\r\n\t\r\n\t\tset Stacks = IMinBJ( STACK_LIMIT, Stacks + 1 )\r\n\t\tif Stacks == 1 then\r\n\t\t\tset Aura = dummyspawn( caster, 0, 'A02R', 0, 0 )\r\n\t\tendif\r\n\t    call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Items\\\\AIso\\\\AIsoTarget.mdl\", caster, \"origin\") )\r\n\t    call KillUnit( caster )\r\n\t    \r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n    private function OnBattleEnd_Condition takes nothing returns boolean\r\n\t    return Stacks != 0\r\n\tendfunction\r\n    \r\n\tprivate function OnBattleEnd takes nothing returns nothing\r\n\t\tset Stacks = 0\r\n\t\tcall RemoveUnit(Aura)\r\n\t\tset Aura = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n    private function OnDamageEvent_Conditions takes nothing returns boolean\r\n\t    return IsUnitHasAbility(udg_DamageEventSource, 'B00A') and udg_IsDamageSpell == false\r\n\tendfunction\r\n    \r\n\tprivate function OnDamageEvent takes nothing returns nothing\r\n\t\tset udg_DamageEventAmount = udg_DamageEventAmount + udg_DamageEventAmount * EXTRA_DAMAGE_PER_STACK * Stacks\r\n\tendfunction\r\n\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t\tcall CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n\t\t\r\n\t\tcall BattleEndGlobal.AddListener(function OnBattleEnd, function OnBattleEnd_Condition)\r\n\t\t\r\n\t\tcall CreateEventTrigger( \"udg_DamageModifierEvent\", function OnDamageEvent, function OnDamageEvent_Conditions )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}