{
  "Id": 50332652,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope PlushDoll initializer init\r\n\t\r\n\tglobals\r\n\t\tprivate constant integer ABILITY_ID = 'A16W'\r\n\t\tprivate constant integer HEAL = 300\r\n\t\tprivate constant string ANIMATION = \"Blood Explosion.mdx\"\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_ID\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local unit caster\r\n\t    local unit target\r\n\t    local integer i\r\n\t    local integer iMax\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = udg_Target\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = randomtarget( caster, 900, \"ally\", RT_NOT_CASTER, 0, 0 )\r\n\t        call textst( udg_string[0] + GetObjectName(ABILITY_ID), caster, 64, 90, 10, 1.5 )\r\n\t        if target == null then\r\n\t            set caster = null\r\n\t            return\r\n\t        endif\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set target = GetSpellTargetUnit()\r\n\t    endif\r\n\t\r\n\t\tset i = 1\r\n\t    set iMax = eyest( caster )\r\n\t    \r\n\t    loop\r\n\t    \texitwhen i > iMax\r\n\t    \tcall healst(caster, target, HEAL)\r\n\t    \tcall DestroyEffect( AddSpecialEffectTarget( ANIMATION, target, \"origin\" ) )\r\n\t    \tif GetUnitState(target, UNIT_STATE_LIFE) > GetUnitState(caster, UNIT_STATE_LIFE) then\r\n\t    \t\tcall SetUnitState( caster, UNIT_STATE_LIFE, GetUnitState( target, UNIT_STATE_LIFE) )\r\n\t    \t\tcall DestroyEffect( AddSpecialEffectTarget( ANIMATION, caster, \"origin\" ) )\r\n\t    \tendif\r\n\t    \tset i = i + 1\r\n    \tendloop\r\n\r\n\t    set caster = null\r\n\t    set target = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    call CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}