{
  "Id": 50332682,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope StaffOfArcana initializer init\r\n\t\r\n\tglobals\r\n\t\tprivate constant integer ABILITY_ID = 'A0ER'\r\n\t\r\n\t\tprivate constant integer EFFECT_ID = 'A0CJ'\r\n\t\tprivate constant integer BUFF_ID = 'B028'\r\n\t\r\n\t\tprivate constant integer SPELL_POWER_TO_ADD = 30\r\n\t    private constant integer DURATION = 30\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_ID\r\n\tendfunction\r\n\t\r\n\tprivate function end takes nothing returns nothing\r\n\t    local integer id = GetHandleId( GetExpiredTimer( ) )\r\n\t    local unit u = LoadUnitHandle( udg_hash, id, StringHash( \"sopp\" ) )\r\n\t\r\n\t    call spdst( u, -LoadReal( udg_hash, GetHandleId( u ), StringHash( \"sopp\" ) ) )\r\n\t    call UnitRemoveAbility( u, EFFECT_ID )\r\n\t    call UnitRemoveAbility( u, BUFF_ID )\r\n\t    call RemoveSavedReal( udg_hash, GetHandleId( u ), StringHash( \"sopp\" ) )\r\n\t    call FlushChildHashtable( udg_hash, id )\r\n\t    \r\n\t    set u = null\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local real toAdd\r\n\t    local unit caster\r\n\t    local integer x\r\n\t    local real t\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set t = udg_Time\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        call textst( udg_string[0] + GetObjectName(ABILITY_ID), caster, 64, 90, 10, 1.5 )\r\n\t        set t = DURATION\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set t = DURATION\r\n\t    endif\r\n\t    \r\n\t    if IsUnitType( caster, UNIT_TYPE_HERO) == false then\r\n\t    \treturn\r\n\t    endif\r\n\t    \r\n\t    set t = timebonus(caster, t)\r\n\t    call eyest( caster )\r\n\r\n        call spdst( caster, -LoadReal( udg_hash, GetHandleId( caster ), StringHash( \"sopp\" ) ) )\r\n    \r\n        if InvisibilitySystem_IsActive(caster) then\r\n        \tset toAdd = 100 * ( GetUnitSpellPower( caster ) - 1 ) + SPELL_POWER_TO_ADD * 2\r\n    \telse\r\n    \t\tset toAdd = SPELL_POWER_TO_ADD\r\n    \tendif\r\n\r\n        call spdst( caster, toAdd )\r\n        call UnitAddAbility( caster, EFFECT_ID )\r\n        \r\n        call InvokeTimerWithUnit( caster, \"sopp\", t, false, function end ) \r\n        call SaveReal( udg_hash, GetHandleId( caster ), StringHash( \"sopp\" ), toAdd ) \r\n\t    \r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t\tcall CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}