{
  "Id": 50332280,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope HPBoss initializer init\r\n\t\r\n\tfunction Trig_HPBoss_Actions takes nothing returns nothing\r\n\t     call BlzLoadTOCFile(\"war3mapImported\\\\myBar.toc\")//keep?\r\n\t\r\n\t    //First Bar\r\n\t    set hpbar1 = BlzCreateSimpleFrame(\"MyBarEx\", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 1)\r\n\t    call BlzFrameSetAbsPoint(hpbar1, FRAMEPOINT_CENTER, 0.4, 0.54)\r\n\t    call BlzFrameSetText(BlzGetFrameByName(\"MyBarExText\",1), \"\")\r\n\t    call BlzFrameSetSize(hpbar1, 0.3, 0.02)\r\n\t    call BlzFrameSetTexture(hpbar1, \"Replaceabletextures\\\\Teamcolor\\\\Teamcolor22.blp\", 0, true)\r\n\t    call BlzFrameSetVisible( hpbar1, false )\r\n\t    \r\n\t    set hpPerc1 = BlzCreateFrameByType(\"TEXT\", \"\", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), \"StandartFrameTemplate\", 0)\r\n\t\tcall BlzFrameSetSize( hpPerc1, 0.1, 0.04 ) \r\n\t    call BlzFrameSetAbsPoint(hpPerc1, FRAMEPOINT_CENTER, 0.573, 0.525)\r\n\t\tcall BlzFrameSetText( hpPerc1, \"|cffbababc100%|r\" )\r\n\t    call BlzFrameSetVisible( hpPerc1, false )\r\n\t    \r\n\t    //Second Bar\r\n\t    set hpbar2 = BlzCreateSimpleFrame(\"MyBarEx\", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 2)\r\n\t    call BlzFrameSetAbsPoint(hpbar2, FRAMEPOINT_CENTER, 0.4, 0.518)\r\n\t    call BlzFrameSetText(BlzGetFrameByName(\"MyBarExText\",2), \"\")\r\n\t    call BlzFrameSetSize(hpbar2, 0.3, 0.02)\r\n\t    call BlzFrameSetTexture(hpbar2, \"Replaceabletextures\\\\Teamcolor\\\\Teamcolor22.blp\", 0, true)\r\n\t    call BlzFrameSetVisible( hpbar2, false )\r\n\t    \r\n\t    set hpPerc2 = BlzCreateFrameByType(\"TEXT\", \"\", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), \"StandartFrameTemplate\", 0)\r\n\t\tcall BlzFrameSetSize( hpPerc2, 0.1, 0.04 )\r\n\t    call BlzFrameSetAbsPoint(hpPerc2, FRAMEPOINT_CENTER, 0.573, 0.503)\r\n\t\tcall BlzFrameSetText( hpPerc2, \"|cffbababc100%|r\" )\r\n\t    call BlzFrameSetVisible( hpPerc2, false )\r\n\tendfunction\r\n\t\r\n\tprivate function OnFightEnd takes nothing returns nothing\r\n\t\tcall AUI_HpBarHide()\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t\tcall BattleEndGlobal.AddListener(function OnFightEnd, null)\r\n\t\r\n\t    set gg_trg_HPBoss = CreateTrigger(  )\r\n\t    call TriggerRegisterTimerExpireEvent( gg_trg_HPBoss, udg_StartTimer )\r\n\t    call TriggerAddAction( gg_trg_HPBoss, function Trig_HPBoss_Actions )\r\n\tendfunction\r\n\t\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}