{
  "Id": 50333400,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_Ressurect_Actions takes nothing returns nothing\r\n    local integer cyclA = 1\r\n    local group g = CreateGroup()\r\n    local unit u\r\n    local integer v\r\n    \r\n    set udg_fightmod[1] = false\r\n    call DisableTrigger( gg_trg_MinionsTeleportation )\r\n    call DisableTrigger( gg_trg_Equality )\r\n    call GroupEnumUnitsInRect( g, udg_Boss_Rect, null )\r\n    loop\r\n        set u = FirstOfGroup(g)\r\n        exitwhen u == null\r\n        if GetUnitTypeId( u ) == 'h00C' then\r\n            call KillUnit( u )\r\n        endif\r\n        call GroupRemoveUnit(g,u)\r\n    endloop\r\n    loop\r\n        exitwhen cyclA > 4\r\n        if GetPlayerSlotState(Player(cyclA - 1)) == PLAYER_SLOT_STATE_PLAYING then\r\n            set udg_number[cyclA + 69] = udg_number[cyclA + 69] + 1\r\n            call SetUnitPositionLoc( udg_hero[cyclA], udg_point[cyclA + 21] )\r\n            call SetUnitFacing( udg_hero[cyclA], 90 )\r\n            if udg_number[4] < 3 then\r\n                call moneyst( udg_hero[cyclA], 125 )\r\n            endif\r\n            call PanCameraToTimedLocForPlayer( Player(cyclA - 1), udg_point[cyclA + 21], 0.00 )\r\n            \r\n            call SecondChance.SetDataUnit(\"caster\", udg_hero[cyclA])\r\n\t\t\tcall SecondChance.Invoke()\r\n        endif\r\n        set cyclA = cyclA + 1\r\n    endloop\r\n    //до выдачи денег\r\n    set udg_number[4] = udg_number[4] + 1\r\n    call FightEnd()\r\n\r\n\t/*if udg_Boss_LvL != 10 then\r\n        call IconFrameDel( \"boss\" )\r\n        \r\n    endif*/\r\n    \r\n    call GroupEnumUnitsOfPlayer(g, Player(10), null )\r\n    loop\r\n        set u = FirstOfGroup(g)\r\n        exitwhen u == null\r\n        if IsMinion(u) and GetUnitAbilityLevel( u, 'Avul') == 0 then\r\n            call KillUnit( u )\r\n        endif\r\n        call GroupRemoveUnit(g,u)\r\n    endloop\r\n\r\n    \r\n    \r\n    call DestroyGroup( g )\r\n    set u = null\r\n    set g = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_Ressurect takes nothing returns nothing\r\n    set gg_trg_Ressurect = CreateTrigger(  )\r\n    call TriggerAddAction( gg_trg_Ressurect, function Trig_Ressurect_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}