{
  "Id": 50332299,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Unitfon initializer init\r\n\r\n\tglobals\r\n\t\tframehandle unitfon\r\n\t\tframehandle uniticon\r\n\t\tframehandle unitname\r\n\t\tframehandle unittool\r\n\tendglobals\r\n\t\r\n\tfunction Trig_UnitFon_Actions takes nothing returns nothing\r\n\t\r\n\t    set unitfon = BlzCreateFrame(\"QuestButtonBaseTemplate\", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0, 0)\r\n\t    call BlzFrameSetAbsPoint(unitfon, FRAMEPOINT_TOP, 0.125, 0.55)\r\n\t    call BlzFrameSetSize(unitfon, 0.25, 0.22)\r\n\t    call BlzFrameSetLevel( unitfon, -1 )\r\n\t\r\n\t\tset uniticon = BlzCreateFrameByType(\"BACKDROP\", \"\", unitfon, \"StandartFrameTemplate\", 0)\r\n\t\tcall BlzFrameSetSize( uniticon, 0.04, 0.04 )\r\n\t\tcall BlzFrameSetPoint(uniticon, FRAMEPOINT_TOPLEFT, unitfon, FRAMEPOINT_TOPLEFT, 0.01,-0.01)   \r\n\t\tcall BlzFrameSetTexture( uniticon, \"ReplaceableTextures\\\\CommandButtons\\\\BTNPolymorph.blp\", 0, true )\r\n\t\r\n\t\tset unitname = BlzCreateFrameByType(\"TEXT\", \"\", unitfon, \"StandartFrameTemplate\", 0)\r\n\t\tcall BlzFrameSetSize( unitname, 0.2, 0.03 )\r\n\t\tcall BlzFrameSetPoint(unitname, FRAMEPOINT_TOP, unitfon, FRAMEPOINT_TOP, 0.04,-0.01) \r\n\t\tcall BlzFrameSetText( unitname, \"\" )\r\n\t\r\n\t\tset unittool = BlzCreateFrameByType(\"TEXT\", \"\", unitfon, \"StandartFrameTemplate\", 0)\r\n\t\tcall BlzFrameSetSize( unittool, 0.23, 0.04 )\r\n\t\tcall BlzFrameSetPoint(unittool, FRAMEPOINT_TOP, unitfon, FRAMEPOINT_TOP, 0.,-0.06) \r\n\t\tcall BlzFrameSetText( unittool, \"\" )\r\n\t\r\n\t\tcall BlzFrameSetVisible(unitfon, false)\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function OnFightStart takes nothing returns nothing\r\n\t\tcall BlzFrameSetVisible(unitfon, false)\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t\tcall CreateEventTrigger( \"udg_FightStartGlobal_Real\", function OnFightStart, null )\r\n\t\t\r\n\t    set gg_trg_UnitFon = CreateTrigger(  )\r\n\t    call TriggerRegisterTimerExpireEventBJ( gg_trg_UnitFon, udg_StartTimer )\r\n\t    call TriggerAddAction( gg_trg_UnitFon, function Trig_UnitFon_Actions )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}