{
  "Id": 50333540,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Mechanic2 initializer init\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetUnitTypeId(udg_DamageEventTarget) == 'h010' and GetUnitLifePercent(udg_DamageEventTarget) <= 75\r\n\tendfunction\r\n\t\r\n\tprivate function Mehanic1Cast takes nothing returns nothing\r\n\t    local integer id = GetHandleId( GetExpiredTimer() )\r\n\t    local unit boss = LoadUnitHandle( udg_hash, id, StringHash( \"bsmc1\" ) )\r\n\t    local unit target \r\n\t            \r\n\t    if GetUnitState( boss, UNIT_STATE_LIFE) <= 0.405 or not( udg_fightmod[0] ) then\r\n\t        call FlushChildHashtable( udg_hash, id )\r\n\t        call DestroyTimer( GetExpiredTimer() )\r\n\t    else\r\n\t    \tset target = randomtarget( boss, 600, \"enemy\", 0, 0, 0 )\r\n\t    \tif target != null then\r\n\t        \tcall IssuePointOrder( boss, \"clusterrockets\", GetUnitX( target ), GetUnitY( target ) )\r\n        \tendif\r\n\t    endif\r\n\t    \r\n\t    set boss = null\r\n\t    set target = null\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t\tlocal unit boss = udg_DamageEventTarget\r\n\t\t\r\n\t    call DisableTrigger( GetTriggeringTrigger() )\r\n\t    call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Other\\\\Volcano\\\\VolcanoDeath.mdl\", boss, \"origin\") )\r\n\t    call UnitAddAbility(boss, 'A0K2')\r\n\t\tcall InvokeTimerWithUnit( boss, \"bsmc1\", bosscast(5), true, function Mehanic1Cast )\r\n\t\t\r\n\t\tset boss = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_Mehanic2 = CreateEventTrigger( \"udg_AfterDamageEvent\", function action, function condition )\r\n\t    call DisableTrigger( gg_trg_Mehanic2 )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}