{
  "Id": 50333555,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Turtle1 initializer init\r\n\t\r\n\tglobals\r\n\t\tprivate constant integer EFFECT_ID = 'A13B'\r\n\t\tprivate constant integer BUFF_ID = 'B05X'\r\n\t\tprivate constant integer BUFF_DURATION = 15\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetUnitTypeId( udg_DamageEventTarget ) == 'h01R'\r\n\tendfunction\r\n\t\r\n\tprivate function CheckHeroes takes unit boss returns nothing\r\n\t\tlocal group g = CreateGroup()\r\n\t    local unit u\r\n\t    local boolean isHeroFound = false\r\n\t\r\n\t\tcall GroupEnumUnitsInRange( g, GetUnitX( boss ), GetUnitY( boss ), 700, null )\r\n        loop\r\n            set u = FirstOfGroup(g)\r\n            exitwhen u == null\r\n            if IsUnitType( u, UNIT_TYPE_HERO) then\r\n                set isHeroFound = true\r\n                exitwhen true\r\n            endif\r\n            call GroupRemoveUnit(g,u)\r\n        endloop\r\n        \r\n        if isHeroFound == false then\r\n            if UnitHasBuffBJ(boss, 'A13B' ) == false then\r\n            \tcall DestroyEffect( AddSpecialEffectTarget(\"Abilities\\\\Spells\\\\NightElf\\\\BattleRoar\\\\RoarCaster.mdl\", boss, \"origin\" ) )\r\n            endif\r\n            call bufallst( boss, boss, EFFECT_ID, 0, 0, 0, 0, BUFF_ID, \"bstt1\", BUFF_DURATION )\r\n        endif\r\n        \r\n\t    call DestroyGroup( g )\r\n\t    set u = null\r\n\t    set g = null\r\n\tendfunction\r\n\t\r\n\tprivate function Turtle1Cast takes nothing returns nothing\r\n\t    local integer id = GetHandleId( GetExpiredTimer() )\r\n\t    local unit boss = LoadUnitHandle( udg_hash, id, StringHash( \"bstt\" ) )\r\n\r\n\t    if GetUnitState( boss, UNIT_STATE_LIFE) <= 0.405 or not( udg_fightmod[0] ) then\r\n\t        call DestroyTimer( GetExpiredTimer() )\r\n\t        call FlushChildHashtable( udg_hash, id )\r\n\t    else\r\n\t        call CheckHeroes(boss)\r\n\t    endif\r\n\t    \r\n\t    \r\n\t    set boss = null\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    call DisableTrigger( GetTriggeringTrigger() )\r\n\t\tcall InvokeTimerWithUnit( udg_DamageEventTarget, \"bstt\", 1, true, function Turtle1Cast )\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_Turtle1 = CreateEventTrigger( \"udg_AfterDamageEvent\", function action, function condition )\r\n\t    call DisableTrigger( gg_trg_Turtle1 )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}