{
  "Id": 50332873,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_WeaponLSW_Conditions takes nothing returns boolean\r\n    return GetItemTypeId(GetManipulatedItem()) == 'I030'\r\nendfunction\r\n\r\nfunction Trig_WeaponLSW_Actions takes nothing returns nothing\r\n    local unit n = GetManipulatingUnit()//udg_hero[GetPlayerId(GetOwningPlayer(GetManipulatingUnit())) + 1]\r\n    local integer i = CorrectPlayer(n)//GetPlayerId(GetOwningPlayer(n)) + 1\r\n    local integer cyclA = 0\r\n    \r\n    set udg_logic[i + 54] = false\r\n    if not( udg_logic[52] ) then\r\n        call DisplayTimedTextToPlayer(GetOwningPlayer(n), 0, 0, 5., \"Set |cff2d9995Weapon|r is now disassembled!\")\r\n        call iconoff( i, SET_WEAPON )\r\n    endif\r\n    \r\n    \r\n    set Event_UnitLoseUltimateWeapon_Hero = n\r\n    set Event_UnitLoseUltimateWeapon_Item = GetManipulatedItem()\r\n    \r\n    set Event_UnitLoseUltimateWeapon_Real = 0.00\r\n    set Event_UnitLoseUltimateWeapon_Real = 1.00\r\n    set Event_UnitLoseUltimateWeapon_Real = 0.00\r\n    \r\n    set cyclA = 0\r\n    set udg_Set_Weapon_Number[i] = 0\r\n    loop\r\n        exitwhen cyclA > 5\r\n        if UnitItemInSlot(n, cyclA) != null and Weapon_Logic(UnitItemInSlot(n, cyclA)) then\r\n            set udg_Set_Weapon_Number[i] = udg_Set_Weapon_Number[i] + 1\r\n        endif\r\n        set cyclA = cyclA + 1\r\n    endloop\r\n    \r\n    set n = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_WeaponLSW takes nothing returns nothing\r\n    set gg_trg_WeaponLSW = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_WeaponLSW, EVENT_PLAYER_UNIT_DROP_ITEM )\r\n    call TriggerAddCondition( gg_trg_WeaponLSW, Condition( function Trig_WeaponLSW_Conditions ) )\r\n    call TriggerAddAction( gg_trg_WeaponLSW, function Trig_WeaponLSW_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}