{
  "Id": 50333004,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope MinotaurW initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant integer ABILITY_ID = 'A0DW'\r\n\t\tprivate constant string ANIMATION = \"Abilities\\\\Spells\\\\Orc\\\\AncestralSpirit\\\\AncestralSpiritCaster.mdl\"\r\n\tendglobals\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_ID\r\n\tendfunction\r\n\t\r\n\tprivate function Use takes unit caster, integer level returns nothing\r\n\t\tlocal real manaToSpend\r\n\t\tlocal real healthToRestore\r\n\t\tlocal real healthLost\r\n\t\r\n\t\tset manaToSpend = GetUnitState( caster, UNIT_STATE_MANA ) / 2\r\n\t\tset healthToRestore = RMaxBJ( 1, manaToSpend * ( 1 + level ) )\r\n\t\tset healthLost = GetUnitState( caster, UNIT_STATE_MAX_LIFE ) - GetUnitState( caster, UNIT_STATE_LIFE )\r\n\t\t\r\n\t    if healthToRestore > healthLost then\r\n\t    \tset manaToSpend = manaToSpend * healthLost / healthToRestore\r\n\t    endif\r\n\t    \r\n\t    call healst( caster, null, healthToRestore )\r\n\t    call spectimeunit( caster, ANIMATION, \"origin\", 1.5 ) \r\n\t    call OnManaSpend_Consume(caster, manaToSpend)\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local integer lvl\r\n\t    local unit caster\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set lvl = udg_Level\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set lvl = udg_Level\r\n\t        call textst( udg_string[0] + GetObjectName(ABILITY_ID), caster, 64, 90, 10, 1.5 )\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n\t    endif    \r\n\t    \r\n\t    call Use(caster, lvl)\r\n\t    \r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_MinW = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( gg_trg_MinW, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n\t    call TriggerAddCondition( gg_trg_MinW, Condition( function condition ) )\r\n\t    call TriggerAddAction( gg_trg_MinW, function action )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}