{
  "Id": 50333155,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_Money_BagW_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A17V'\r\nendfunction\r\n\r\nfunction Trig_Money_BagW_Actions takes nothing returns nothing\r\n    local unit caster\r\n    local unit target\r\n    local unit attachedUnit\r\n    local integer lvl\r\n    local real mana\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n        set lvl = udg_Level\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 900, \"all\", RT_MINION, 0, 0 )\r\n        set lvl = udg_Level\r\n        call textst( udg_string[0] + GetObjectName('A17V'), caster, 64, 90, 10, 1.5 )\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n    endif\r\n\r\n    set mana = 35 + lvl * 15\r\n\r\n    call manast( caster, null, mana )\r\n    call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Undead\\\\DarkRitual\\\\DarkRitualTarget.mdl\", GetUnitX(target), GetUnitY(target)) )\r\n    call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Other\\\\Stampede\\\\StampedeMissileDeath.mdl\", caster, \"origin\") )\r\n\r\n    set attachedUnit = LoadUnitHandle( udg_hash, GetHandleId( caster ), StringHash( \"mbgqtt\" ) )\r\n    if attachedUnit != null and GetUnitAbilityLevel(attachedUnit, 'A17U') > 0 then\r\n    \tcall manast( caster, attachedUnit, mana )\r\n    \tcall DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Other\\\\Stampede\\\\StampedeMissileDeath.mdl\", attachedUnit, \"origin\") )\r\n    endif\r\n    call KillUnit(target)\r\n    \r\n    set caster = null\r\n    set target = null\r\n    set attachedUnit = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_Money_BagW takes nothing returns nothing\r\n    set gg_trg_Money_BagW = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_Money_BagW, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_Money_BagW, Condition( function Trig_Money_BagW_Conditions ) )\r\n    call TriggerAddAction( gg_trg_Money_BagW, function Trig_Money_BagW_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}