{
  "Id": 50333157,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope MoneyBagR initializer init\r\n\t\r\n\tglobals\r\n\t    private constant integer ABILITY_ID = 'A17Y'\r\n\t    \r\n\t    private constant string ANIMATION = \"Abilities\\\\Spells\\\\Other\\\\Stampede\\\\StampedeMissileDeath.mdl\"\r\n\t    \r\n\t    private constant integer MONEY_GAIN_INITIAL = 25\r\n\t    private constant integer MONEY_GAIN_PER_LEVEL = 15\r\n\t    \r\n\t    private constant integer HEAL_GAIN_INITIAL = 100\r\n\t    private constant integer HEAL_GAIN_PER_LEVEL = 50\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_ID and combat( GetSpellAbilityUnit(), true, GetSpellAbilityId() )\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local integer lvl\r\n\t    local unit caster\r\n\t    local unit attachedUnit\r\n\t    local integer money\r\n\t    local integer heal\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set lvl = udg_Level\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set lvl = udg_Level\r\n\t        call textst( udg_string[0] + GetObjectName(ABILITY_ID), caster, 64, 90, 10, 1.5 )\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n\t    endif\r\n\t    \r\n\t    set money = MONEY_GAIN_INITIAL + MONEY_GAIN_PER_LEVEL * lvl\r\n\t    set heal = HEAL_GAIN_INITIAL + HEAL_GAIN_PER_LEVEL * lvl\r\n\t    \r\n\t    call healst( caster, null, heal )\r\n\t    call DestroyEffect( AddSpecialEffectTarget( ANIMATION, caster, \"chest\") )\r\n\t    set attachedUnit = LoadUnitHandle( udg_hash, GetHandleId( caster ), StringHash( \"mbgqtt\" ) )\r\n\t    \r\n\t    if udg_fightmod[3] == false then\r\n\t\t    if GetUnitAbilityLevel(attachedUnit, 'A17U') > 0 then\r\n\t\t    \tcall moneyst(attachedUnit, money)\r\n\t\t    endif\r\n\t\t    call moneyst(caster, money)\r\n\t    endif\r\n\t    \r\n\t    set attachedUnit = null\r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_Money_BagR = CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}