{
  "Id": 50333034,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope InfernalE initializer init\r\n\r\n\tfunction Trig_InfernalE_Conditions takes nothing returns boolean\r\n\t    return GetLearnedSkill() == 'A1A5'\r\n\tendfunction\r\n\t\r\n\tfunction Trig_InfernalE_Actions takes nothing returns nothing\r\n\t    local unit u = GetLearningUnit()\r\n\t    local integer lvl = 3+GetUnitAbilityLevel(u, 'A1A5')\r\n\t    local integer id = GetHandleId(u)\r\n\t    \r\n\t    call UnitAddAbility( u, 'A1A6')\r\n\t    call UnitAddAbility( u, 'A1A7')\r\n\t    call SetUnitAbilityLevel(u, 'A1A6', lvl )\r\n\t    \r\n\t    call textst( \"|cFF57E5C6\" + I2S(GetUnitAbilityLevel(u, 'A1A6')-1), u, 64, GetRandomReal( 80, 100 ), 12, 1 )\r\n\t    call SaveReal( udg_hash, id, StringHash( \"infe\" ), 0 )\r\n\t    call SaveReal( udg_hash, id, StringHash( \"infen\" ), GetUnitState( u, UNIT_STATE_MAX_LIFE) * 0.2 )\r\n\t    \r\n\t    set u = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function OnBetween_Condition takes nothing returns boolean\r\n\t\treturn GetUnitAbilityLevel( Event_BetweenUnit_Hero, 'A1A5') > 0\r\n\tendfunction\r\n\t\t\r\n\tprivate function OnBetween takes nothing returns nothing\r\n\t\tlocal unit hero = Event_BetweenUnit_Hero\r\n\t\t\r\n\t\tcall platest( hero, 10 )\r\n\t    call SaveReal( udg_hash, GetHandleId( hero ), StringHash( \"infen\" ), GetUnitState( hero, UNIT_STATE_MAX_LIFE) * 0.2 )\r\n\t    \r\n\t    set hero = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_InfernalE = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( gg_trg_InfernalE, EVENT_PLAYER_HERO_SKILL )\r\n\t    call TriggerAddCondition( gg_trg_InfernalE, Condition( function Trig_InfernalE_Conditions ) )\r\n\t    call TriggerAddAction( gg_trg_InfernalE, function Trig_InfernalE_Actions )\r\n\t    \r\n\t    call CreateEventTrigger( \"Event_BetweenUnit\", function OnBetween, function OnBetween_Condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}