{
  "Id": 50333588,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Berserk3 initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant integer HEAL_AMOUNT = 35\r\n\t\tprivate constant integer TICK = 1\r\n\t\tprivate constant string START_ANIMATION = \"Abilities\\\\Spells\\\\NightElf\\\\BattleRoar\\\\RoarCaster.mdl\"\r\n\tendglobals\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetUnitTypeId(udg_DamageEventTarget) == 'e00F' and GetUnitLifePercent(udg_DamageEventTarget) <= 30\r\n\tendfunction\r\n\t\r\n\tprivate function HealCast takes nothing returns nothing\r\n\t    local integer id = GetHandleId( GetExpiredTimer( ) )\r\n\t    local unit boss = LoadUnitHandle( udg_hash, id, StringHash( \"boss_berserk_heal\" ) )\r\n\t    local real healAmount\r\n\r\n\t    if IsUnitDead(boss) or not( udg_fightmod[0] ) then\r\n\t        call DestroyTimer( GetExpiredTimer() )\r\n\t        call FlushChildHashtable( udg_hash, id )\r\n\t    else\r\n\t    \tset healAmount = HEAL_AMOUNT * SpellPower_GetBossSpellPower()\r\n\t        call SetUnitState( boss, UNIT_STATE_LIFE, GetUnitState( boss, UNIT_STATE_LIFE ) + healAmount )\r\n            call textst( \"|c0000C800+\" + R2SI( healAmount ), boss, 64, GetRandomReal( 45, 135 ), 8, 1 )\r\n\t    endif\r\n\r\n\t    set boss = null\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t\tlocal unit boss = udg_DamageEventTarget\r\n\t\t\r\n\t    call DisableTrigger( GetTriggeringTrigger() )\r\n\t    call DestroyEffect( AddSpecialEffect( START_ANIMATION, GetUnitX( boss ), GetUnitY( boss ) ) )\r\n\t    call InvokeTimerWithUnit( boss, \"boss_berserk_heal\", TICK, true, function HealCast )\r\n\t    \r\n\t    set boss = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_Berserk3 = CreateEventTrigger( \"udg_AfterDamageEvent\", function action, function condition )\r\n\t    call DisableTrigger( gg_trg_Berserk3 )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}