{
  "Id": 50332952,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope MagnataurP initializer init\r\n\t\r\n\tglobals\r\n\t\tprivate constant integer ABILITY_ID = 'A098'\r\n\t\t\r\n\t\tprivate constant integer CHANCE_INITIAL = 1\r\n\t    private constant integer CHANCE_PER_LEVEL = 3\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t\tif udg_IsDamageSpell then\r\n\t\t\t//call BJDebugMsg(\"udg_IsDamageSpell\")\r\n\t\t\treturn false\r\n\t\tendif\r\n\t\tif IsUnitAlly( AfterAttack.TriggerUnit, GetOwningPlayer( AfterAttack.TargetUnit ) ) then\r\n\t\t\t//call BJDebugMsg(\"IsUnitAlly\")\r\n\t\t\treturn false\r\n\t\tendif\r\n\t\tif GetUnitAbilityLevel( udg_DamageEventSource, ABILITY_ID) == 0 then\r\n\t\t\t//call BJDebugMsg(\"GetUnitAbilityLevel( udg_DamageEventSource, ABILITY_ID) == 0\")\r\n\t\t\treturn false\r\n\t\tendif\r\n\t\tif LuckChance( AfterAttack.TriggerUnit, CHANCE_INITIAL + CHANCE_PER_LEVEL * GetUnitAbilityLevel( AfterAttack.TriggerUnit, ABILITY_ID) ) then\r\n\t\t\t//call BJDebugMsg(\"luck\")\r\n\t\t\treturn true\r\n\t\tendif\r\n\t\t//call BJDebugMsg(\"unluck\")\r\n\t    return false\r\n\tendfunction\r\n\t\r\n\tprivate function Cast takes nothing returns nothing\r\n\t\tlocal integer id = GetHandleId( GetExpiredTimer() )\r\n\t    local unit caster = LoadUnitHandle(udg_hash, id, StringHash(\"magnataur_e\") )\r\n\t    local integer lvl = GetUnitAbilityLevel( caster, ABILITY_ID)\r\n\t    local integer rand = GetRandomInt( 1, 3 )\r\n\t    local trigger triggerCast\r\n\t\r\n\t    if rand == 1 then\r\n\t        set triggerCast = gg_trg_MagnataurQ\r\n\t    elseif rand == 2 then\r\n\t        set triggerCast = gg_trg_MagnataurW\r\n\t    else\r\n\t        set triggerCast = gg_trg_MagnataurR\r\n\t    endif\r\n\t    call CastLib_CastRandomAbility( caster, triggerCast, lvl )\r\n\t        \r\n\t    set triggerCast = null\r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing   \r\n\t    call InvokeTimerWithUnit( AfterAttack.GetDataUnit(\"caster\"), \"magnataur_e\", 0.01, false, function Cast )\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_MagnataurP = AfterAttack.AddListener(function action, function condition)\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}