{
  "Id": 50333375,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope WicerdR initializer init\r\n\t\r\n\tglobals\r\n\t\tprivate constant integer ABILITY_ID = 'A17O'\r\n\t\t\r\n\t\tprivate constant integer DAMAGE_INITIAL = 60\r\n\t\tprivate constant integer DAMAGE_PER_LEVEL = 40\r\n\t\tprivate constant integer AREA_SIZE = 600\r\n\t\tprivate constant real STUN_DURATION = 3\r\n\t\tprivate constant string ANIMATION = \"Abilities\\\\Weapons\\\\FrostWyrmMissile\\\\FrostWyrmMissile.mdl\"\r\n\tendglobals\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_ID\r\n\tendfunction\r\n\t\r\n\tprivate function Cast takes unit caster, integer level returns nothing\r\n\t\tlocal real damage \r\n\t    local group g = CreateGroup()\r\n\t    local unit u\r\n\t\r\n\t\tset damage = DAMAGE_INITIAL + DAMAGE_PER_LEVEL * level\r\n\t    call GroupEnumUnitsInRange( g, GetUnitX( caster ), GetUnitY( caster ), AREA_SIZE, null )\r\n\t    loop\r\n\t        set u = FirstOfGroup(g)\r\n\t        exitwhen u == null\r\n\t        if unitst( u, caster, \"enemy\" ) then\r\n\t\t\t\tcall DestroyEffect( AddSpecialEffect( ANIMATION, GetUnitX(u), GetUnitY(u) ) )\r\n\t    \t\tif WicerdFreeze_IsFrozen(u) then\r\n\t                call UnitStun(caster, u, STUN_DURATION )\r\n\t    \t\tendif\r\n\t    \t\tcall UnitDamageTarget(caster, u, damage, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n\t    \t\tcall WicerdFreeze_Cast( caster, u )\r\n\t        endif\r\n\t        call GroupRemoveUnit(g,u)\r\n\t    endloop\r\n\t    \r\n\t    call DestroyGroup( g )\r\n\t    set u = null\r\n\t    set g = null\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local integer lvl\r\n\t    local unit caster\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set lvl = udg_Level\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set lvl = udg_Level\r\n\t        call textst( udg_string[0] + GetObjectName(ABILITY_ID), caster, 64, 90, 10, 1.5 )\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n\t    endif\r\n\t    \r\n\t    call Cast(caster, lvl)\r\n\r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_WicerdR = CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}