{
  "Id": 50333374,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope WicerdW initializer init\r\n\t\r\n\tglobals\r\n\t\tprivate constant integer ABILITY_ID = 'A17M'\r\n\t\r\n\t    private constant real STUN_DURATION_INITIAL = 1.5\r\n\t    private constant real STUN_DURATION_PER_LEVEL = 0.5\r\n\t    private constant integer DAMAGE_INITIAL = 100\r\n\t    private constant integer DAMAGE_PER_LEVEL = 50\r\n\t    private constant string HIT_ANIMATION = \"Abilities\\\\Weapons\\\\FrostWyrmMissile\\\\FrostWyrmMissile.mdl\"\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_ID\r\n\tendfunction\r\n\t\r\n\tprivate function Cast takes unit caster, unit target, integer level returns nothing\r\n\t\tlocal real dmg\r\n\t    local real stunDuration\r\n\t\r\n\t\tset stunDuration = STUN_DURATION_INITIAL + STUN_DURATION_PER_LEVEL * level\r\n\t    set dmg = DAMAGE_INITIAL + DAMAGE_PER_LEVEL * level\r\n\r\n\t    call DestroyEffect( AddSpecialEffect( HIT_ANIMATION, GetUnitX(target), GetUnitY(target) ) )\r\n\t    if WicerdFreeze_IsFrozen(target) then\r\n\t        call UnitStun(caster, target, stunDuration )\r\n\t    endif\r\n\t    call UnitDamageTarget(caster, target, dmg, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n\t    call WicerdFreeze_Cast( caster, target )\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local unit caster\r\n\t    local unit target\r\n\t    local integer lvl\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = udg_Target\r\n\t        set lvl = udg_Level\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = randomtarget( caster, 900, \"enemy\", 0, 0, 0 )\r\n\t        set lvl = udg_Level\r\n\t        call textst( udg_string[0] + GetObjectName(ABILITY_ID), caster, 64, 90, 10, 1.5 )\r\n\t        if target == null then\r\n\t            set caster = null\r\n\t            return\r\n\t        endif\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set target = GetSpellTargetUnit()\r\n\t        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n\t    endif\r\n\t    \r\n\t    call Cast(caster, target, lvl)\r\n\t    \r\n\t    set caster = null\r\n\t    set target = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_WicerdW = CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}