{
  "Id": 50333374,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope WicerdW initializer init\r\n\t\r\n\tglobals\r\n\t    private constant real STUN_DURATION_INITIAL = 1.5\r\n\t    private constant real STUN_DURATION_PER_LEVEL = 0.5\r\n\tendglobals\r\n\t\r\n\tfunction Trig_WicerdW_Conditions takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == 'A17M'\r\n\tendfunction\r\n\t\r\n\tfunction Trig_WicerdW_Actions takes nothing returns nothing\r\n\t    local unit caster\r\n\t    local unit target\r\n\t    local integer lvl\r\n\t    local real dmg\r\n\t    local real t\r\n\t    local real stunDuration\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = udg_Target\r\n\t        set lvl = udg_Level\r\n\t\tset t = udg_Time\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = randomtarget( caster, 900, \"all\", RT_NOT_CASTER, 0, 0 )\r\n\t        set lvl = udg_Level\r\n\t\t\tset t = 10\r\n\t        call textst( udg_string[0] + GetObjectName('A17M'), caster, 64, 90, 10, 1.5 )\r\n\t        if target == null then\r\n\t            set caster = null\r\n\t            return\r\n\t        endif\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set target = GetSpellTargetUnit()\r\n\t        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n\t\t\tset t = 10\r\n\t    endif\r\n\t    set stunDuration = STUN_DURATION_INITIAL + STUN_DURATION_PER_LEVEL * lvl\r\n\t    set dmg = 50 + ( 50 * lvl )\r\n\t    set t = timebonus(caster, t)\r\n\t    \r\n\t    call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Weapons\\\\FrostWyrmMissile\\\\FrostWyrmMissile.mdl\", GetUnitX(target), GetUnitY(target) ) )\r\n\t    if GetUnitAbilityLevel( target, 'B07J' ) > 0 or GetUnitAbilityLevel( target, 'B07K' ) > 0 then\r\n\t    \tcall UnitDamageTarget(caster, target, dmg, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n\t        call UnitStun(caster, target, stunDuration )\r\n\t    endif\r\n\t    call freezest( caster, target, t, lvl )\r\n\t    \r\n\t    set caster = null\r\n\t    set target = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_WicerdW = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( gg_trg_WicerdW, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n\t    call TriggerAddCondition( gg_trg_WicerdW, Condition( function Trig_WicerdW_Conditions ) )\r\n\t    call TriggerAddAction( gg_trg_WicerdW, function Trig_WicerdW_Actions )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}