{
  "Id": 50333408,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "library BossCastLib requires BuffDeleteLib\r\n\r\n\tglobals\r\n\t\tprivate real BossInterval = 0\r\n\tendglobals\r\n\t\r\n\tpublic function AddInterval takes integer value returns nothing\r\n\t\tset BossInterval = BossInterval + (value/100.)\r\n\tendfunction\r\n\r\n    function bosscast takes real r returns real\r\n        local real n = r\r\n\r\n\t\tset n = n + BossInterval\r\n\r\n        if IsHardcoreEnabled then\r\n            set n = n - (0.2*r)\r\n        endif\r\n        if udg_Endgame > 1 then\r\n            set n = n - (0.1*(udg_Endgame-1))\r\n        endif\r\n        if n < 0.2*r then\r\n            set n = 0.2*r\r\n        endif\r\n        return n\r\n    endfunction\r\n    \r\n    public function SetDisappear takes unit boss, boolean value  returns nothing\r\n    \tcall SaveBoolean(udg_hash, GetHandleId(boss), StringHash( \"boss_disappear\" ), value )\r\n    endfunction\r\n    \r\n    public function IsDisappear takes unit boss  returns boolean\r\n    \treturn LoadBoolean(udg_hash, GetHandleId(boss), StringHash( \"boss_disappear\" ) )\r\n    endfunction\r\n    \r\n    function ReplaceBoss takes unit oldUnit, integer newUnitType returns unit\r\n    \tlocal unit newBoss\r\n    \t\r\n    \tcall DelBuff( oldUnit, false )\r\n    \tcall ShowUnit( oldUnit, false)\r\n    \tset newBoss = CreateUnit(GetOwningPlayer(oldUnit), newUnitType, GetUnitX(oldUnit), GetUnitY(oldUnit), GetUnitFacing(oldUnit))\r\n        call SaveUnitHandle( udg_hash, GetHandleId( LoadTimerHandle( udg_hash, GetHandleId( oldUnit ), StringHash( \"aggro\" ) ) ), StringHash( \"aggro\" ), newBoss )\r\n        call GroupRemoveUnit( udg_Bosses, oldUnit )\r\n\r\n        if bossbar == oldUnit then\r\n            set bossbar = newBoss\r\n        endif\r\n        if bossbar1 == oldUnit then\r\n            set bossbar1 = newBoss\r\n        endif\r\n        \r\n        if GetUnitAbilityLevel( oldUnit, 'A1HP' ) > 0 then\r\n        \tcall UnitAddAbility(newBoss, 'A1HP')\r\n\t\t\tcall UnitAddAbility(newBoss, 'A1HQ')\r\n        endif\r\n        \r\n    \treturn newBoss\r\n    endfunction\r\n\r\nendlibrary",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}