{
  "Id": 50333450,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope OgreMagi3 initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant integer ID_BOSS = 'h00Q'\r\n\t\tprivate constant integer HP_REQUIRE = 25\r\n\t\t\r\n\t\tprivate constant integer CHARGE_TICK = 1\r\n        private constant integer CHARGE_TIME = 4\r\n        private constant integer ID_CHARGE_ANIMATION = 'A1HU'\r\n        private constant integer ID_CHARGE_ANIMATION_BUFF = 'B0AX'\r\n\t\t\r\n\t\tpublic trigger Trigger = null\r\n\tendglobals\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetUnitTypeId(udg_DamageEventTarget) == ID_BOSS and GetUnitLifePercent(udg_DamageEventTarget) <= HP_REQUIRE\r\n\tendfunction\r\n\t\r\n\tprivate function OgreCast takes nothing returns nothing\r\n        local integer id = GetHandleId( GetExpiredTimer() )\r\n        local integer counter = LoadInteger( udg_hash, id, StringHash( \"ogre_magi_3_cast\" ) ) + 1\r\n        local unit boss = LoadUnitHandle( udg_hash, id, StringHash( \"ogre_magi_3_cast\" ) )\r\n        \r\n        if counter >= CHARGE_TIME then\r\n            if IsUnitAlive(boss) and udg_fightmod[0] then\r\n                call pausest( boss, -1 )\r\n                call UnitRemoveAbility( boss, ID_CHARGE_ANIMATION)\r\n                call UnitRemoveAbility( boss, ID_CHARGE_ANIMATION_BUFF)\r\n                \r\n                call SetUnitState( boss, UNIT_STATE_LIFE, GetUnitState( boss, UNIT_STATE_MAX_LIFE ) )\r\n\t    \t\tcall DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Orc\\\\WarStomp\\\\WarStompCaster.mdl\", boss, \"origin\") )\r\n            endif\r\n            call FlushChildHashtable( udg_hash, id )\r\n            call DestroyTimer( GetExpiredTimer() )\r\n        else\r\n            call SaveInteger( udg_hash, id, StringHash( \"ogre_magi_3_cast\" ), counter )\r\n            if IsUnitAlive(boss) then\r\n                call SetUnitAnimation( boss, \"spell\" )\r\n            endif\r\n        endif\r\n        \r\n        set boss = null\r\n    endfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    call DisableTrigger( GetTriggeringTrigger() )\r\n\t    \r\n\t    call pausest( udg_DamageEventTarget, 1 )\r\n        call SetUnitAnimation( udg_DamageEventTarget, \"spell\" )\r\n        call UnitAddAbility( udg_DamageEventTarget, ID_CHARGE_ANIMATION )\r\n\t    call InvokeTimerWithUnit(udg_DamageEventTarget, \"ogre_magi_3_cast\", CHARGE_TICK, true, function OgreCast)\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set Trigger = CreateTrigger(  )\r\n\t    call DisableTrigger( Trigger )\r\n\t    call TriggerRegisterVariableEvent( Trigger, \"udg_AfterDamageEvent\", EQUAL, 1.00 )\r\n\t    call TriggerAddCondition( Trigger, Condition( function condition ) )\r\n\t    call TriggerAddAction( Trigger, function action )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}