{
  "Id": 50332315,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope ResFrame initializer init\r\n\t\r\n\tglobals\r\n\t    framehandle resback\r\n\t    framehandle restext\r\n\tendglobals\r\n\t\r\n\tfunction ResTrame takes nothing returns nothing\r\n\t    local framehandle frame\r\n\t    local real x = 1.2\r\n\t    local real y = 1.2\r\n\t    \r\n\t    set resback = BlzCreateFrameByType(\"BACKDROP\", \"\", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), \"StandartFrameTemplate\", 0)\r\n\t    call BlzFrameSetAbsPoint(resback, FRAMEPOINT_CENTER, 0.35, 0.565)\t\r\n\t    call BlzFrameSetSize(resback, 0.026*x, 0.012*y)\r\n\t    call BlzFrameSetTexture( resback, \"war3mapImported\\\\BTNfeed-icon-red-1_result.blp\",0, true)\r\n\t    call BlzFrameSetVisible( resback, false )\r\n\t    \r\n\t    set frame = BlzCreateFrameByType(\"BACKDROP\", \"\", resback, \"StandartFrameTemplate\", 0)\r\n\t    call BlzFrameSetPoint( frame, FRAMEPOINT_CENTER, resback, FRAMEPOINT_CENTER, -0.0075*x, 0*y )\r\n\t    call BlzFrameSetSize(frame, 0.01*x, 0.01*y)\r\n\t    call BlzFrameSetTexture( frame, \"ReplaceableTextures\\\\CommandButtons\\\\BTNAnkh.blp\",0, true)\r\n\t        \r\n\t    set restext = BlzCreateFrameByType(\"TEXT\", \"\", resback, \"StandartFrameTemplate\", 0)\r\n\t    call BlzFrameSetSize( restext, 0.01*x, 0.01*y )\r\n\t    call BlzFrameSetPoint(restext, FRAMEPOINT_BOTTOMLEFT, resback, FRAMEPOINT_BOTTOMLEFT, 0.013*x,0.001*y) \r\n\t    call BlzFrameSetText( restext, \"0\" )\r\n\t    call BlzFrameSetTextAlignment( restext, TEXT_JUSTIFY_CENTER, TEXT_JUSTIFY_RIGHT)\r\n\t    \r\n\t    set frame = null\r\n\tendfunction\r\n\t\r\n\tprivate function OnFightEnd takes nothing returns nothing\r\n\t\tcall BlzFrameSetVisible( resback, false )\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t\tcall BattleEndGlobal.AddListener(function OnFightEnd, null)\r\n\t\r\n\t    set gg_trg_ResTrame = CreateTrigger(  )\r\n\t    call TriggerRegisterTimerExpireEvent( gg_trg_ResTrame, udg_StartTimer )\r\n\t    call TriggerAddAction( gg_trg_ResTrame, function ResTrame )\r\n\tendfunction\r\n\t\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}