{
  "Id": 50333464,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_Arah2_Conditions takes nothing returns boolean\r\n    return GetUnitTypeId(udg_DamageEventTarget) == 'h00K' and GetUnitLifePercent(udg_DamageEventTarget) <= 35\r\nendfunction\r\n\r\nfunction Trig_Arah2_Actions takes nothing returns nothing\r\n    local integer i\r\n    local integer k\r\n    local location spawnLoc\r\n    local location rectLoc = GetRectCenter( udg_Boss_Rect )\r\n    local unit newUnit\r\n    local unit boss = udg_DamageEventTarget\r\n    \r\n    call DisableTrigger( GetTriggeringTrigger() )\r\n    call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\NightElf\\\\BattleRoar\\\\RoarCaster.mdl\", boss, \"origin\") )\r\n    set i = 1\r\n    loop\r\n        exitwhen i > 4\r\n        set spawnLoc = PolarProjectionBJ( rectLoc, 2000, 45 + 90 * i )\r\n        set k = 1\r\n        loop\r\n            exitwhen k > 8\r\n\t    \tset newUnit = Arah0_SummonArachnid(boss, spawnLoc, GetRandomDirectionDeg() )\r\n            \r\n            if udg_fightmod[4] then\r\n                call UnitApplyTimedLife( newUnit, 'BTLF', 60)\r\n            endif\r\n            set k = k + 1\r\n        endloop\r\n        set i = i + 1\r\n    endloop\r\n    \r\n    call RemoveLocation(spawnLoc)\r\n    call RemoveLocation(rectLoc)\r\n    set rectLoc = null\r\n\tset spawnLoc = null\r\n\tset newUnit = null\r\n\tset boss = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_Arah2 takes nothing returns nothing\r\n    set gg_trg_Arah2 = CreateTrigger(  )\r\n    call DisableTrigger( gg_trg_Arah2 )\r\n    call TriggerRegisterVariableEvent( gg_trg_Arah2, \"udg_AfterDamageEvent\", EQUAL, 1.00 )\r\n    call TriggerAddCondition( gg_trg_Arah2, Condition( function Trig_Arah2_Conditions ) )\r\n    call TriggerAddAction( gg_trg_Arah2, function Trig_Arah2_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}