{
  "Id": 50332351,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope CheatNext initializer init\r\n\t\r\n\tprivate function Trig_Cheatnext_Conditions takes nothing returns boolean\r\n\t    return SubString(GetEventPlayerChatString(), 0, 5) == \"-next\"\r\n\tendfunction\r\n\t\r\n\tprivate function CheatNextSquad takes nothing returns nothing\r\n\t    call KillUnit( GetEnumUnit() )\r\n\tendfunction\r\n\t\r\n\tprivate function CheatNext takes nothing returns nothing\r\n\t    local integer cyclA\r\n\t    local string str\r\n\r\n\t    if udg_Boss_LvL >= 10 then\r\n\t        set udg_Boss_LvL = 10\r\n\t        set str = I2S(udg_Boss_LvL)\r\n\t    else\r\n\t        set str = I2S(udg_Boss_LvL + 1)\r\n\t    endif\r\n\t    \r\n\t    call BJDebugMsg(\"Boss Level set to \" + str + \".\")\r\n\t\r\n\t    if IsUnitGroupEmptyBJ(udg_Bosses) then\r\n\t        call Between( BATTLE_TYPE_MAIN, STATE_REST )\r\n\t    else\r\n\t        call ForGroupBJ( GetUnitsOfPlayerMatching(Player(10), null), function CheatNextSquad )\r\n\t    endif\r\n\tendfunction\r\n\t\r\n\tprivate function Trig_Cheatnext_Actions takes nothing returns nothing\r\n\t    local string s = I2S( S2I(SubString(GetEventPlayerChatString(), 6, 8)) - 1 )\r\n\t    local integer cyclA = 1\r\n\t    local integer cyclB\r\n\t    \r\n\t    loop\r\n\t        exitwhen cyclA > 4\r\n\t        set cyclB = 1\r\n\t        loop\r\n\t            exitwhen cyclB > 6\r\n\t            call UnitRemoveAbility( udg_unit[cyclA + 17], Boss_Info[udg_Boss_LvL][cyclB] )\r\n\t            call UnitRemoveAbility( udg_UNIT_INFORMANT, Boss_Info[udg_Boss_LvL][cyclB] )\r\n\t            set cyclB = cyclB + 1\r\n\t        endloop\r\n\t        set cyclA = cyclA + 1\r\n\t    endloop\r\n\t\tcall BlzFrameSetVisible( rpkmod,false)\r\n\t    if s != \"\" and S2I(s) >= 0 and S2I(s) <= 9 then\r\n\t        set udg_Boss_LvL = S2I(s)\r\n\t    endif\r\n\t    \r\n\t    call ItemRandomizerLib_AllRemoveRewards()\r\n\t    call TimerStart( CreateTimer(), 0.1, false, function CheatNext )\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    local integer cyclA = 0\r\n\t    set gg_trg_Cheatnext = CreateTrigger()\r\n\t    loop\r\n\t        exitwhen cyclA > 3\r\n\t            call TriggerRegisterPlayerChatEvent( gg_trg_Cheatnext, Player(cyclA), \"-next\", false )\r\n\t        set cyclA = cyclA + 1\r\n\t    endloop\r\n\t    call TriggerAddCondition( gg_trg_Cheatnext, Condition( function Trig_Cheatnext_Conditions ) )\r\n\t    call TriggerAddAction( gg_trg_Cheatnext, function Trig_Cheatnext_Actions )\r\n\tendfunction\r\n\t\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}