{
  "Id": 50332862,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope MoonSetCast initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant integer BUFF_REQUIRE = 'B08W'\r\n\t\tprivate constant integer MANA_SPEND = 40\r\n\t\tprivate constant integer HASH_KEY = StringHash(\"moon_set_mana\")\r\n\tendglobals\r\n\r\n\t//===========================================================================\r\n\tprivate function OnInvisibility_Condition takes nothing returns boolean\r\n\t    return GetUnitAbilityLevel( EnterInvisibility.GetDataUnit(\"unit\"), BUFF_REQUIRE) > 0\r\n\tendfunction\r\n\t\r\n\tprivate function OnInvisibility takes nothing returns nothing\r\n\t\tlocal unit hero = EnterInvisibility.GetDataUnit(\"unit\")\r\n\t\t\r\n\t    call MoonTrigger( hero )\r\n\t    \r\n\t    set hero = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function OnManaSpent_Condition takes nothing returns boolean\r\n\t    return GetUnitAbilityLevel( ManaSpent.GetDataUnit(\"unit\"), BUFF_REQUIRE) > 0\r\n\tendfunction\r\n\t\r\n\tprivate function Cast takes unit hero, integer counter, integer id returns nothing\r\n\t\tlocal integer i = 1\r\n\t\tlocal integer iMax = counter / MANA_SPEND\r\n\t\tlocal integer newCounter = counter - iMax * MANA_SPEND\r\n\t\t\r\n\t\tcall SaveInteger(udg_hash, id, HASH_KEY, newCounter )\r\n\t\r\n\t\tif iMax > i then\r\n\t\t\tloop\r\n\t\t\t\texitwhen i > iMax\r\n\t\t\t\tcall MoonTrigger( hero )\r\n\t\t\t\tset i = i + 1\r\n\t\t\tendloop\r\n\t\telse\r\n\t\t\tcall MoonTrigger( hero )\r\n\t\tendif\r\n\tendfunction\r\n\t\r\n\tprivate function OnManaSpent takes nothing returns nothing\r\n\t\tlocal unit hero = ManaSpent.GetDataUnit(\"unit\")\r\n\t\tlocal integer id = GetHandleId(hero)\r\n\t\tlocal integer manaUsed = ManaSpent.GetDataInteger(\"amount\")\r\n\t\tlocal integer counter = LoadInteger(udg_hash, id, HASH_KEY ) + manaUsed\r\n\t\t\r\n\t\tif counter >= MANA_SPEND then\r\n\t\t\tcall Cast(hero, counter, id)\r\n\t\telse\r\n\t\t\tcall SaveInteger(udg_hash, id, HASH_KEY, counter )\r\n\t\tendif\r\n\r\n\t    set hero = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    call EnterInvisibility.AddListener(function OnInvisibility, function OnInvisibility_Condition)\r\n\t    call ManaSpent.AddListener(function OnManaSpent, function OnManaSpent_Condition)\r\n\tendfunction\r\n\r\nendscope\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}