{
  "Id": 50333706,
  "Comment": "Could be library requiring BossKill (if that was a library too\r\ninstead of calling BossKill_Actions_on_u",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope MoneyAL initializer init\r\n\r\n    private function Trig_AL_Money_Conditions takes nothing returns boolean\r\n        return udg_fightmod[4] and GetOwningPlayer(GetDyingUnit()) == Player(10) and IsUnitInGroup(GetDyingUnit(), udg_Bosses) \r\n    endfunction\r\n    \r\n    private function UnitCheck takes unit u returns boolean\r\n        return LoadBoolean(udg_hash, GetHandleId(u), OverloadArena_STRING_HASH)\r\n    endfunction\r\n\r\n    private function Trig_AL_Money_Actions takes nothing returns nothing\r\n        local integer i\r\n        local real money = udg_number[9]\r\n        \r\n        call BossKill_Actions_on_u( GetDyingUnit() ) // also removes u from udg_Bosses\r\n        if UnitCheck(GetDyingUnit()) then\r\n            if udg_number[9] < OverloadArena_GOLD_CAP then\r\n                set udg_number[9] = udg_number[9] + OverloadArena_GOLD_EXTRA_PER_KILL\r\n            endif\r\n            \r\n            set i = 1\r\n            loop\r\n                exitwhen i > 4\r\n                if GetPlayerSlotState(Player(i - 1)) == PLAYER_SLOT_STATE_PLAYING then\r\n                    call moneyst( udg_hero[i], R2I(money * ExtraArenaGeneral_GetGoldGainMultiplier()) )\r\n                endif\r\n                set i = i + 1\r\n            endloop\r\n        endif\r\n    endfunction\r\n\r\n    //===========================================================================\r\n    private function init takes nothing returns nothing\r\n        set gg_trg_AL_Money = CreateTrigger(  )\r\n        call TriggerRegisterAnyUnitEventBJ( gg_trg_AL_Money, EVENT_PLAYER_UNIT_DEATH )\r\n        call TriggerAddCondition( gg_trg_AL_Money, Condition( function Trig_AL_Money_Conditions ) )\r\n        call TriggerAddAction( gg_trg_AL_Money, function Trig_AL_Money_Actions )\r\n    endfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}