{
  "Id": 50333517,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope GhostKnight1 initializer init\r\n\t\r\n\tglobals\r\n\t\tprivate constant integer COOLDOWN = 6\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetUnitTypeId( udg_DamageEventTarget ) == 'n008' \r\n\tendfunction\r\n\t\r\n\tprivate function UnitConditions takes unit boss, unit target, unit potentialTarget returns boolean\r\n\t\tif IsUnitAlly(target, GetOwningPlayer(potentialTarget)) then\r\n\t\t\treturn false\r\n\t\tendif\r\n\t\tif InvisibilitySystem_IsActive(potentialTarget) then\r\n\t\t\treturn false\r\n\t\tendif\r\n\t\tif BlzIsUnitInvulnerable(potentialTarget) then\r\n\t\t\treturn false\r\n\t\tendif\r\n\t    if GetUnitLifePercent(potentialTarget) > GetUnitLifePercent(target) then\r\n\t    \treturn true\r\n\t    endif\r\n\t    return false\r\n\tendfunction\r\n\t\r\n\tprivate function CastCoil takes unit boss returns nothing\r\n\t    local group heroes = DeathSystem_GetAliveHeroGroupCopy()\r\n\t\tlocal unit u\r\n\t\tlocal unit target = null\r\n\t\t\r\n\t\tloop\r\n\t\t\tset u = FirstOfGroup(heroes)\r\n\t\t\texitwhen u == null\r\n\t\t\tif UnitConditions(boss, target, u ) then \r\n\t\t\t\tset target = u\r\n\t\t\tendif\r\n\t\t\tcall GroupRemoveUnit(heroes, u)\r\n\t\tendloop\r\n\t\r\n        call DestroyGroup(heroes)\r\n\t\tset heroes = null\r\n\t\tset u = null\r\n\t\t\r\n        if target == null then\r\n\t        return\r\n        endif\r\n        call dummyspawn( boss, 1, 'A03M', 0, 0 )\r\n        call IssueTargetOrder( bj_lastCreatedUnit, \"deathcoil\", target )\r\n        call SetUnitAnimation( boss, \"spell\" )\r\n        call QueueUnitAnimation( boss, \"stand\" )\r\n\r\n\t\tset target = null\r\n\tendfunction\r\n\t\r\n\tpublic function GhostKnightCast1 takes nothing returns nothing\r\n\t    local integer id = GetHandleId( GetExpiredTimer() )\r\n\t    local unit boss = LoadUnitHandle( udg_hash, id, StringHash( \"bsgk1\" ) )\r\n\t\r\n\t    if IsUnitDead( boss ) or not( udg_fightmod[0] ) then\r\n\t        call DestroyTimer( GetExpiredTimer() )\r\n\t        call FlushChildHashtable( udg_hash, id )\r\n\t    else\r\n\t    \tcall CastCoil(boss)\r\n\t    endif\r\n\r\n\t    set boss = null\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    call DisableTrigger( GetTriggeringTrigger() )\r\n\t\r\n\t\tcall InvokeTimerWithUnit( udg_DamageEventTarget, \"bsgk1\", bosscast(COOLDOWN), true, function GhostKnightCast1 )\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_GhostKnight1 = CreateEventTrigger( \"udg_AfterDamageEvent\", function action, function condition )\r\n\t    call DisableTrigger( gg_trg_GhostKnight1 )\r\n\tendfunction\r\n\t\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}