{
  "Id": 50333506,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Chief5 initializer init\r\n\r\n\tglobals\r\n\t\tpublic trigger Trigger1 = null\r\n\t\tpublic trigger Trigger2 = null\r\n\t\tpublic trigger Trigger3 = null\r\n\t\t\r\n\t\tprivate constant string ANIMATION = \"Abilities\\\\Spells\\\\Human\\\\DispelMagic\\\\DispelMagicTarget.mdl\"\r\n\tendglobals\r\n\r\n\tprivate function condition1 takes nothing returns boolean\r\n\t    return GetUnitTypeId( udg_DamageEventTarget ) == 'h01X' and GetUnitLifePercent(udg_DamageEventTarget) <= 80\r\n\tendfunction\r\n\t\r\n\tprivate function condition2 takes nothing returns boolean\r\n\t    return GetUnitTypeId( udg_DamageEventTarget ) == 'h01X' and GetUnitLifePercent(udg_DamageEventTarget) <= 50\r\n\tendfunction\r\n\t\r\n\tprivate function condition3 takes nothing returns boolean\r\n\t    return GetUnitTypeId( udg_DamageEventTarget ) == 'h01X' and GetUnitLifePercent(udg_DamageEventTarget) <= 30\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t\tlocal unit boss = udg_DamageEventTarget\r\n\t    local integer i = 1\r\n\t\r\n\t    call DisableTrigger( GetTriggeringTrigger() )\r\n\t \r\n        call DestroyEffect( AddSpecialEffect( ANIMATION, GetUnitX(boss), GetUnitY(boss) ) ) \r\n\t\tcall DelBuff( boss, false )   \r\n\t\tloop\r\n\t\t\texitwhen i > 4\r\n\t\t\tif IsUnitAlive( udg_hero[i] ) then\r\n        \t\tcall DestroyEffect( AddSpecialEffect( ANIMATION, GetUnitX(udg_hero[i]), GetUnitY(udg_hero[i]) ) ) \r\n\t\t\t\tcall DelBuff( udg_hero[i], false )\r\n\t\t\tendif\r\n\t\t\tset i = i + 1\r\n\t\tendloop\r\n\t\tset boss = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set Trigger1 = CreateEventTrigger( \"udg_AfterDamageEvent\", function action, function condition1 )\r\n\t    call DisableTrigger( Trigger1 )\r\n\t    \r\n\t    set Trigger2 = CreateEventTrigger( \"udg_AfterDamageEvent\", function action, function condition2 )\r\n\t    call DisableTrigger( Trigger1 )\r\n\t    \r\n\t    set Trigger3 = CreateEventTrigger( \"udg_AfterDamageEvent\", function action, function condition3 )\r\n\t    call DisableTrigger( Trigger1 )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}