{
  "Id": 50333481,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Manadragon1 initializer init\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetUnitTypeId( udg_DamageEventTarget ) == 'e004' and GetUnitLifePercent(udg_DamageEventTarget) <= 95\r\n\tendfunction\r\n\t\r\n\tprivate function ManaBurn takes unit boss, real burn returns nothing\r\n\t\tlocal group heroes\r\n\t\tlocal unit u\r\n\t\t\r\n\t\tif GetOwningPlayer(boss) != Player(10) then\r\n\t    \treturn\r\n    \tendif\r\n    \tset heroes = DeathSystem_GetAliveHeroGroupCopy()\r\n\t\t\r\n\t\tloop\r\n\t\t\tset u = FirstOfGroup(heroes)\r\n\t\t\texitwhen u == null\r\n\t\t\tcall SetUnitState( u, UNIT_STATE_MANA, RMaxBJ(0, GetUnitState( u, UNIT_STATE_MANA ) - ( burn * SpellPower_GetBossSpellPower() ) ) )\r\n            call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Undead\\\\ReplenishMana\\\\ReplenishManaCasterOverhead.mdl\", u, \"origin\") )\r\n\t\t\tcall GroupRemoveUnit(heroes, u)\r\n\t\tendloop\r\n\t\r\n\t\tcall DestroyGroup(heroes)\r\n\t\tset heroes = null\r\n\t\tset u = null\r\n\tendfunction\r\n\t\r\n\tprivate function ManadrCast takes nothing returns nothing\r\n\t    local integer id = GetHandleId( GetExpiredTimer() )\r\n\t    local unit boss = LoadUnitHandle( udg_hash, id, StringHash( \"bsmd\" ) ) \r\n\t    local real r = LoadReal( udg_hash, GetHandleId( boss ), StringHash( \"bsmd\" ) )\r\n\r\n\t    if GetUnitState( boss, UNIT_STATE_LIFE) <= 0.405 or not( udg_fightmod[0] ) then\r\n\t        call FlushChildHashtable( udg_hash, id )\r\n\t        call DestroyTimer( GetExpiredTimer() )\r\n\t    else\r\n        \tcall ManaBurn(boss, r)\r\n\t    endif\r\n\t\r\n\t    set boss = null\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local integer id = GetHandleId( udg_DamageEventTarget )\r\n\t\r\n\t    call DisableTrigger( GetTriggeringTrigger() )\r\n\t    call ManaBurn(udg_DamageEventTarget, 20)\r\n\t    \r\n\t    if LoadTimerHandle( udg_hash, id, StringHash( \"bsmd\" ) ) == null  then\r\n\t        call SaveTimerHandle( udg_hash, id, StringHash( \"bsmd\" ), CreateTimer() )\r\n\t    endif\r\n\t    set id = GetHandleId( LoadTimerHandle( udg_hash, id, StringHash( \"bsmd\" ) ) ) \r\n\t    call SaveUnitHandle( udg_hash, id, StringHash( \"bsmd\" ), udg_DamageEventTarget )\r\n\t    call SaveReal( udg_hash, GetHandleId( udg_DamageEventTarget ), StringHash( \"bsmd\" ), 20 )\r\n\t\tcall TimerStart( LoadTimerHandle( udg_hash, GetHandleId( udg_DamageEventTarget ), StringHash( \"bsmd\" ) ), bosscast(8), true, function ManadrCast )\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_Manadragon1 = CreateEventTrigger( \"udg_AfterDamageEvent\", function action, function condition )\r\n\t    call DisableTrigger( gg_trg_Manadragon1 )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}