{
  "Id": 50333129,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope GunMasterE initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant integer ABILITY_ID = 'A19J'\r\n\t\t\r\n\t\tprivate constant integer CHANCE_INITIAL = 10\r\n\t\tprivate constant integer CHANCE_PER_LEVEL = 5\r\n\t\t\r\n\t\tprivate constant integer ARMOR_TO_LOSE = 1\r\n\t\t\r\n\t\tprivate constant integer DAMAGE_TO_EXTRA = 225\r\n\t\tprivate constant integer ARMOR_TO_LOSE_EXTRA = 1\r\n\t\t\r\n\t\tprivate constant string ANIMATION = \"Abilities\\\\Weapons\\\\GyroCopter\\\\GyroCopterMissile.mdl\"\r\n\tendglobals\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t\tlocal integer level = GetUnitAbilityLevel(udg_DamageEventSource, ABILITY_ID)\r\n\t\tif level == 0 then\r\n\t\t\treturn false\r\n\t\telseif udg_IsDamageSpell == false then\r\n\t\t\treturn false\r\n\t\telseif udg_DamageEventAmount <= 0 then\r\n\t\t\treturn false\r\n\t\telseif combat( udg_DamageEventSource, false, 0 ) == false then\r\n\t\t\treturn false\r\n\t\telseif LuckChance(udg_DamageEventSource, CHANCE_INITIAL + CHANCE_PER_LEVEL * level ) == false then\r\n\t\t\treturn false\r\n\t\telseif IsUnitType( udg_DamageEventTarget, UNIT_TYPE_HERO) then\r\n\t\t\treturn false\r\n\t\telseif IsUnitDead( udg_DamageEventTarget ) then\r\n\t\t\treturn false\r\n\t\tendif\r\n\t    return true\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local unit target = udg_DamageEventTarget\r\n\t    local integer armorToLose = ARMOR_TO_LOSE\r\n\t    \r\n\t    if udg_DamageEventAmount >= DAMAGE_TO_EXTRA then\r\n\t    \tset armorToLose = armorToLose + ARMOR_TO_LOSE_EXTRA\r\n\t    endif\r\n\t    \r\n        call BlzSetUnitArmor( target, BlzGetUnitArmor(target) - armorToLose )\r\n        call DestroyEffect( AddSpecialEffect( ANIMATION, GetUnitX( target ), GetUnitY( target ) ) )\r\n\t\r\n\t    set target = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t\tcall CreateEventTrigger( \"udg_DamageModifierEvent\", function action, function condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}