{
  "Id": 50332339,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "library ModesFrameSet\r\n\t\r\n\tglobals\r\n\t    integer array DB_ModesFrame_Mode[4][3]//LR/UD\r\n\t    integer array DB_ModesFrame_Rotation[4][3]//LR/UD\r\n\t    \r\n\t    constant integer BASE_BOSS_ARMOR = 10\r\n\t    \r\n\t    public constant integer MODE_ROW_SIZE = 4\r\n\t    public constant integer MODE_COLUMN_SIZE = 2\r\n\tendglobals\r\n\t\r\n\tpublic function Init takes nothing returns nothing\r\n\t    set udg_DB_ModesFrame_AbilityNum = 5\r\n\t    set udg_DB_ModesFrame_Ability[1] = 'A15C'\r\n\t    set udg_DB_ModesFrame_Ability[2] = 'A0D2'\r\n\t    set udg_DB_ModesFrame_Ability[3] = 'A0JO'\r\n\t    set udg_DB_ModesFrame_Ability[4] = 'A09D'\r\n\t    set udg_DB_ModesFrame_Ability[5] = 'A0F2'\r\n\t    \r\n\t    set DB_ModesFrame_Mode[1][1] = 'A03K'\r\n\t    set DB_ModesFrame_Mode[2][1] = 'A0BK'\r\n\t    set DB_ModesFrame_Mode[3][1] = 'A0WT'\r\n\t    set DB_ModesFrame_Mode[4][1] = 'A1BM'\r\n\t    set DB_ModesFrame_Mode[1][2] = 'A0HK'\r\n\t    set DB_ModesFrame_Mode[2][2] = 'A0HL'\r\n\t    set DB_ModesFrame_Mode[3][2] = 'A0HM'\r\n\t    set DB_ModesFrame_Mode[4][2] = 'A1BX'\r\n\t    \r\n\t    set udg_DB_ModesFrame_RotationLR = 5\r\n\t    set udg_DB_ModesFrame_RotationUD = 2\r\n\t    set udg_DB_ModesFrame_RotationNum = udg_DB_ModesFrame_RotationLR*udg_DB_ModesFrame_RotationUD\r\n\t    set DB_ModesFrame_Rotation[1][1] = 'A0F3'\r\n\t    set DB_ModesFrame_Rotation[2][1] = 'A0OQ'\r\n\t    set DB_ModesFrame_Rotation[3][1] = 'A0PZ'\r\n\t    set DB_ModesFrame_Rotation[4][1] = 'A0YQ'\r\n\t    set DB_ModesFrame_Rotation[5][1] = 'A0YR'\r\n\t    set DB_ModesFrame_Rotation[1][2] = 'A0YS'\r\n\t    set DB_ModesFrame_Rotation[2][2] = 'A0PY'\r\n\t    set DB_ModesFrame_Rotation[3][2] = 'A10P'\r\n\t    set DB_ModesFrame_Rotation[4][2] = 'A19C'\r\n\t    set DB_ModesFrame_Rotation[5][2] = 'A1BJ'\r\n\t    \r\n\t    set udg_base = 0\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_MerryCristmas\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_MasterDisguise\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_EldRichMoon\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_AllRandom\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_Purity_of_Power\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_Freedom_of_Choice\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_SheepIsGood\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_CorruptedWorld\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_Orbomination\r\n\t    set udg_DB_Rotation[BaseNum()] = gg_trg_Im_Legend\r\n\tendfunction\r\n\r\nendlibrary",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}