{
  "Id": 50332294,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "globals\r\n \tframehandle array infrtlp\r\nendglobals\r\n\r\nfunction Trig_InfoFrame_DB takes nothing returns nothing\r\n\tset udg_DB_InfoFrame_Number = 3\r\n    set udg_DB_InfoFrame_Name[1] = \"|cffffcc00Gold|r\"\r\n    set udg_DB_InfoFrame_Name[2] = \"|cffbe81f7Spell power|r\"\r\n    set udg_DB_InfoFrame_Name[3] = \"|cffd7df01Luck|r\"\r\n    set udg_DB_InfoFrame_Tooltip[1] = \"Gold can be obtained by defeating bosses, from certain abilities and items, and in additional arenas.\"\r\n    set udg_DB_InfoFrame_Tooltip[2] = \"Spell Power increases damage and healing from abilities and items. Numbers colored |cffbe81f7this way|r scale with spell power.|n|n|cffffcc00Example:|r |cffbe81f7100|r damage + 30% Spell Power = 130 damage.\"\r\n    set udg_DB_InfoFrame_Tooltip[3] = \"Luck increases the chance of effects triggering. Numbers colored |cffd7df01this way|r scale with luck.|n|n|cffffcc00Example:|r |cffd7df012%|r chance + 5% luck = 7%.\"\r\nendfunction\r\n\r\nfunction Trig_InfoFrame_Actions takes nothing returns nothing\r\n\tlocal framehandle faceHover\r\n\tlocal integer cyclA\r\n\tlocal integer cyclAEnd \r\n\t\r\n\tcall Trig_InfoFrame_DB()\r\n\t\r\n    set cyclA = 1\r\n    set cyclAEnd = udg_DB_InfoFrame_Number\r\n\tloop\r\n\t\texitwhen cyclA > cyclAEnd\r\n\t\tset faceHover = BlzCreateFrameByType(\"FRAME\", \"\", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0),\"\", 0)\r\n        call BlzFrameSetSize(faceHover, 0.08, 0.02)\r\n        call BlzFrameSetAbsPoint(faceHover, FRAMEPOINT_LEFT, 0.375+(cyclA*0.088), 0.588)\r\n        \r\n        call SetStableTool( faceHover, udg_DB_InfoFrame_Name[cyclA], udg_DB_InfoFrame_Tooltip[cyclA] )\r\n\t\tset cyclA = cyclA + 1\r\n\tendloop\r\n\r\n\tset faceHover = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_InfoFrame takes nothing returns nothing\r\n    set gg_trg_InfoFrame = CreateTrigger(  )\r\n    call TriggerRegisterTimerEventSingle( gg_trg_InfoFrame, 0.10 )\r\n    call TriggerAddAction( gg_trg_InfoFrame, function Trig_InfoFrame_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}