{
  "Id": 50333693,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "library IAMoney initializer init requires Money, ExtraArenaGeneral\r\n\t\r\n\tglobals\r\n\t\tprivate integer MoneyGain = 0\r\n\tendglobals\r\n\t\r\n\tpublic function ResetMoneyValue takes nothing returns nothing\r\n\t\tset MoneyGain = 0\r\n\tendfunction\r\n\t\r\n\tpublic function Result takes nothing returns nothing\r\n\t\tcall DisplayTimedTextToForce( bj_FORCE_ALL_PLAYERS, 10, \"|cffffcc00Total Gold Gain: |r\" + I2S(MoneyGain) + \".\" )\r\n\tendfunction\r\n\t\r\n\tfunction Trig_IA_Money_Conditions takes nothing returns boolean\r\n\t    return udg_fightmod[2] and GetUnitAbilityLevel( GetDyingUnit(), 'A0CZ' ) > 0 //and GetOwningPlayer(GetDyingUnit()) == Player(10)\r\n\tendfunction\r\n\t\r\n\tfunction Trig_IA_Money_Actions takes nothing returns nothing\r\n\t    local integer i\r\n\t    local integer id = GetHandleId( GetDyingUnit() )\r\n\t    local integer money = LoadInteger( udg_hash, id, StringHash( \"goldIA\" ) )\r\n\t    \r\n\t    if money == 0 then\r\n\t    \treturn\r\n\t    endif\r\n\t    set money = R2I( money * ExtraArenaGeneral_GetGoldGainMultiplier() )\r\n\t    \r\n\t    set MoneyGain = MoneyGain + money\r\n\t    set i = 1\r\n\t    loop\r\n\t        exitwhen i > 4\r\n\t        if udg_hero[i] != null then\r\n\t            call moneyst( udg_hero[i], money )\r\n\t        endif\r\n\t        set i = i + 1\r\n\t    endloop\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_IA_Money = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( gg_trg_IA_Money, EVENT_PLAYER_UNIT_DEATH )\r\n\t    call TriggerAddCondition( gg_trg_IA_Money, Condition( function Trig_IA_Money_Conditions ) )\r\n\t    call TriggerAddAction( gg_trg_IA_Money, function Trig_IA_Money_Actions )\r\n\tendfunction\r\n\t\r\nendlibrary",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}