{
  "Id": 50332296,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Itemfon initializer init\r\n\tglobals\r\n\t\tframehandle itemfon\r\n\t\tframehandle itemicon\r\n\t\tframehandle itemname\r\n\t\tframehandle itemtool\r\n\tendglobals\r\n\t\r\n\tfunction Trig_ItemFon_Actions takes nothing returns nothing\r\n\t\r\n\t    set itemfon = BlzCreateFrame(\"QuestButtonBaseTemplate\", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0, 0)\r\n\t    call BlzFrameSetAbsPoint(itemfon, FRAMEPOINT_TOP, 0.125, 0.55)\r\n\t    call BlzFrameSetSize(itemfon, 0.25, 0.22)\r\n\t\tcall BlzFrameSetLevel( itemfon, -1 )\r\n\t\r\n\t\tset itemicon = BlzCreateFrameByType(\"BACKDROP\", \"\", itemfon, \"StandartFrameTemplate\", 0)\r\n\t\tcall BlzFrameSetSize( itemicon, 0.04, 0.04 )\r\n\t\tcall BlzFrameSetPoint(itemicon, FRAMEPOINT_TOPLEFT, itemfon, FRAMEPOINT_TOPLEFT, 0.01,-0.01)   \r\n\t\tcall BlzFrameSetTexture( itemicon, \"ReplaceableTextures\\\\CommandButtons\\\\BTNPolymorph.blp\", 0, true )\r\n\t\r\n\t\tset itemname = BlzCreateFrameByType(\"TEXT\", \"\", itemfon, \"StandartFrameTemplate\", 0)\r\n\t\tcall BlzFrameSetSize( itemname, 0.2, 0.04 )\r\n\t\tcall BlzFrameSetPoint(itemname, FRAMEPOINT_TOP, itemfon, FRAMEPOINT_TOP, 0.04,-0.01) \r\n\t\tcall BlzFrameSetText( itemname, \"\" )\r\n\t\r\n\t\tset itemtool = BlzCreateFrameByType(\"TEXT\", \"\", itemfon, \"StandartFrameTemplate\", 0)\r\n\t\tcall BlzFrameSetSize( itemtool, 0.23, 0.14 )\r\n\t\tcall BlzFrameSetPoint(itemtool, FRAMEPOINT_TOP, itemfon, FRAMEPOINT_TOP, 0.,-0.06) \r\n\t\tcall BlzFrameSetText( itemtool, \"\" )\r\n\t\r\n\t\tcall BlzFrameSetVisible(itemfon, false)\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function OnFightStart takes nothing returns nothing\r\n\t\tcall BlzFrameSetVisible(itemfon, false)\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t\tcall CreateEventTrigger( \"udg_FightStartGlobal_Real\", function OnFightStart, null )\r\n\t\t\r\n\t    set gg_trg_ItemFon = CreateTrigger(  )\r\n\t    call TriggerRegisterTimerExpireEventBJ( gg_trg_ItemFon, udg_StartTimer )\r\n\t    call TriggerAddAction( gg_trg_ItemFon, function Trig_ItemFon_Actions )\r\n\tendfunction\r\n\t\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}