{
  "Id": 50332412,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope ChameleonTarot initializer init\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == 'A1I9' and GetItemTypeId(GetSpellTargetItem()) != 'I0EL'\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t\tlocal unit caster = GetSpellAbilityUnit()\r\n\t\tlocal item itemTarget = GetSpellTargetItem()\r\n\t    local integer i\r\n\t    local item itemCheck\r\n\t    local integer newItemType\r\n\t    local boolean isValidTarget = false\r\n\r\n\t    set i = 0\r\n\t    loop\r\n\t        exitwhen i > 5\r\n\t        set itemCheck = UnitItemInSlot(caster, i)\r\n\t        if itemTarget == itemCheck then\r\n\t        \tset newItemType = ItemRandomizerLib_GetRandomItemType()\r\n\t            call Inventory_ReplaceItemByNew(caster, itemTarget, newItemType)\r\n\t            set isValidTarget = true\r\n\t            exitwhen true\r\n\t        endif\r\n\t        set i = i + 1\r\n\t    endloop\r\n\t    \r\n\t    if isValidTarget then\r\n\t    \tcall DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Human\\\\Resurrect\\\\ResurrectTarget.mdl\", caster, \"origin\") )\r\n\t\t    call statst( caster, 2, 2, 2, 0, true )\r\n\t\t    call stazisst( caster, GetItemOfTypeFromUnitBJ( caster, 'I0EL') )\r\n\t    endif\r\n\t    \r\n\t    set itemTarget = null\r\n\t    set itemCheck = null\r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    local trigger trig = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( trig, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n\t    call TriggerAddCondition( trig, Condition( function condition ) )\r\n\t    call TriggerAddAction( trig, function action )\r\n\t    set trig = null\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}