{
  "Id": 50332409,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Cytrine initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant integer ABILITY_ID = 'A1IU'\r\n\t\t\r\n\t\tprivate constant integer DAMAGE = 250\r\n\t\tprivate constant integer EFFECT = 'A054'\r\n\t\t\r\n\t\tprivate constant string ANIMATION = \"war3mapImported\\\\WhiteChakraExplosion.mdx\"\r\n\tendglobals\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_ID\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local integer i\r\n\t    local integer iMax = 1\r\n\t    local unit caster\r\n\t    local unit target\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = udg_Target\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = randomtarget( caster, 900, \"enemy\", 0, 0, 0 )\r\n\t        call textst( udg_string[0] + GetObjectName(ABILITY_ID), caster, 64, 90, 10, 1.5 )\r\n\t        if target == null then\r\n\t            set caster = null\r\n\t            return\r\n\t        endif\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set target = GetSpellTargetUnit()\r\n\t    endif\r\n\t    \r\n\t    set i = 1\r\n\t    set iMax = eyest( caster )\r\n\t    loop\r\n\t        exitwhen i > iMax\r\n\t        call UnitDamageTarget( caster, target, DAMAGE, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n\t        call DestroyEffect( AddSpecialEffect( ANIMATION, GetUnitX( target ), GetUnitY( target ) ) )\r\n            call UnitAddAbility( caster, EFFECT )\r\n\t        set i = i + 1\r\n\t    endloop\r\n\t        \r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    call CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}