{
  "Id": 50332419,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope FishSoup initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant real BASE_HEAL = 0.08\r\n\t\tprivate constant real HEAL_PER_POTION = 0.02\r\n\tendglobals\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == 'A0AH'\r\n\tendfunction\r\n\t\r\n\tprivate function CalculateHeal takes unit caster returns real\r\n\t\tlocal real heal = BASE_HEAL\r\n\t\tlocal integer i\r\n\t\tlocal item itemCheck\r\n\t\t\r\n\t\tset i = 0\r\n\t\tloop\r\n\t        exitwhen i >= 6\r\n\t        set itemCheck = UnitItemInSlot(caster, i)\r\n\t        if itemCheck != null and IsPotion(itemCheck)  then\r\n\t            set heal = heal + HEAL_PER_POTION * BlzGetItemIntegerField(itemCheck, ITEM_IF_NUMBER_OF_CHARGES)\r\n\t        endif\r\n\t        set i = i + 1\r\n\t    endloop\r\n\t    \r\n\t    set heal = RMinBJ(1, heal)\r\n\t\t\r\n\t\tset itemCheck = null\r\n\t\treturn heal\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local integer cyclB\r\n\t    local unit caster\r\n\t    local real heal\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        call textst( udg_string[0] + GetObjectName('A0AH'), caster, 64, 90, 10, 1.5 )\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t    endif\r\n\t    \r\n\t    set heal = CalculateHeal(caster)\r\n\t    \r\n        set cyclB = 1\r\n        loop\r\n            exitwhen cyclB > 4\r\n            if unitst( udg_hero[cyclB], caster, \"ally\" ) then\r\n                call healst( GetSpellAbilityUnit(), udg_hero[cyclB], heal * GetUnitState( udg_hero[cyclB], UNIT_STATE_MAX_LIFE) )\r\n                call spectimeunit( udg_hero[cyclB], \"Abilities\\\\Spells\\\\Human\\\\Heal\\\\HealTarget.mdl\", \"origin\", 2 )\r\n            endif\r\n            set cyclB = cyclB + 1\r\n        endloop\r\n\t    \r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_Fish_Soup = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( gg_trg_Fish_Soup, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n\t    call TriggerAddCondition( gg_trg_Fish_Soup, Condition( function condition ) )\r\n\t    call TriggerAddAction( gg_trg_Fish_Soup, function action )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}