{
  "Id": 50332481,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope NecroWool initializer init\r\n\r\n\tfunction Trig_Necro_Wool_Conditions takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == 'A0YM'\r\n\tendfunction\r\n\t\r\n\tfunction Trig_Necro_Wool_Actions takes nothing returns nothing\r\n\t    local group g = CreateGroup()\r\n\t    local unit u\r\n\t    local integer cyclA = 1\r\n\t    local integer cyclAEnd \r\n\t    local unit caster\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        call textst( udg_string[0] + GetObjectName('A0YM'), caster, 64, 90, 10, 1.5 )\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t    endif\r\n\t    \r\n\t    set cyclAEnd = eyest( caster )\r\n\t  \r\n\t    call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Human\\\\Polymorph\\\\PolyMorphDoneGround.mdl\", caster, \"origin\" ) )\r\n\t     loop\r\n\t        exitwhen cyclA > cyclAEnd\r\n\t        call GroupEnumUnitsInRange( g, GetUnitX( caster ), GetUnitY( caster ), 600, null )\r\n\t        loop\r\n\t            set u = FirstOfGroup(g)\r\n\t            exitwhen u == null\r\n\t            if IsUnitAlly( u, GetOwningPlayer( caster ) ) and not( IsUnitType( u, UNIT_TYPE_HERO) ) and not( IsUnitType( u, UNIT_TYPE_ANCIENT) ) and GetUnitAbilityLevel( u, 'Avul') == 0 then\r\n\t                call UnitAddAbility( u, 'A0YO')\r\n\t            endif\r\n\t            call GroupRemoveUnit(g,u)\r\n\t        endloop\r\n\t        set cyclA = cyclA + 1\r\n\t    endloop\r\n\t    \r\n\t    set u = null\r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_Necro_Wool = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( gg_trg_Necro_Wool, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n\t    call TriggerAddCondition( gg_trg_Necro_Wool, Condition( function Trig_Necro_Wool_Conditions ) )\r\n\t    call TriggerAddAction( gg_trg_Necro_Wool, function Trig_Necro_Wool_Actions )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}