{
  "Id": 50332487,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope NewbornPhoenix initializer init\r\n\t\r\n\tglobals\r\n\t    constant integer NEWBORN_PHOENIX_DURATION = 10\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t\tif udg_fightmod[3] then\r\n\t\t\t//call BJDebugMsg(\"udg_fightmod[3]\")\r\n\t\t\treturn false\r\n\t\telseif inv( AfterAttack.GetDataUnit(\"target\"), 'I05W') == 0 then\r\n\t\t\t//call BJDebugMsg(\"inv( AfterAttack.GetDataUnit(\\\"target\\\"), 'I05W') == 0\")\r\n\t\t\treturn false\r\n\t\telseif combat( AfterAttack.GetDataUnit(\"target\"), false, 0) == false then\r\n\t\t\t//call BJDebugMsg(\"combat( AfterAttack.GetDataUnit(\\\"target\\\"), false, 0) == false\")\r\n\t\t\treturn false\r\n\t\telseif IsUnitDead( AfterAttack.GetDataUnit(\"target\") ) then\r\n\t\t\t//call BJDebugMsg(\"IsUnitDead( AfterAttack.GetDataUnit(\\\"target\\\") )\")\r\n\t\t\treturn false\r\n\t\telseif AfterAttack.GetDataReal(\"damage\") < GetUnitState( AfterAttack.GetDataUnit(\"target\"), UNIT_STATE_LIFE) then\r\n\t\t\t//call BJDebugMsg(\"AfterAttack.GetDataReal(\\\"damage\\\") < GetUnitState( AfterAttack.GetDataUnit(\\\"target\\\"), UNIT_STATE_LIFE)\")\r\n\t\t\treturn false\r\n\t\tendif\r\n\t\treturn true\r\n\tendfunction\r\n\t\r\n\t/*private function Cast takes nothing returns nothing\r\n\t    local integer id = GetHandleId( GetExpiredTimer( ) )\r\n\t    local unit caster = LoadUnitHandle( udg_hash, id, StringHash( \"nbph\" ) )\r\n\t    \r\n\t    \r\n\t    call DestroyTimer( GetExpiredTimer() )\r\n\t    \r\n\t    set caster = null\r\n\tendfunction*/\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local unit caster = AfterAttack.GetDataUnit(\"target\")\r\n\t    local integer id = GetHandleId( caster )\r\n\t\r\n\t\tset udg_DamageEventType = udg_DamageTypeIgnore\r\n\t\tcall bufallst(caster, null, 'A0NA', 'A0MJ', 0, 0, 0, 'B09W', \"nbphf\", NEWBORN_PHOENIX_DURATION )\r\n\t\tcall healst( caster, null, GetUnitState( caster, UNIT_STATE_MAX_LIFE) )\r\n\t    call manast( caster, null, GetUnitState( caster, UNIT_STATE_MAX_MANA) )\r\n\t    call DestroyEffect( AddSpecialEffectTarget(\"Abilities\\\\Spells\\\\Human\\\\ReviveHuman\\\\ReviveHuman.mdl\", caster, \"origin\" ) )\r\n\t\r\n\t    //call InvokeTimerWithUnit( caster, \"nbph\", 0.01, false, function Cast )\r\n\t\r\n\t\tcall stazisst( caster, GetItemOfTypeFromUnitBJ( caster, 'I05W') )\r\n\t\r\n\t\tset caster = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    call AfterAttack.AddListener(function action, function condition)\r\n\tendfunction\r\n\r\nendscope\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}