{
  "Id": 50332552,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope TarotWorld initializer init\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == 'A13F'\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local integer cyclA \r\n\t    \r\n\t    if not(udg_logic[80]) then\r\n\t    \tcall IconFrame( \"World\", \"war3mapImported\\\\BTNINV_Inscription_TarotLords.blp\", \"Tarot Card: World\", \"Upgrade |cff60C445uniques|r of all heroes until the end of the battle.\" )\r\n\t        \r\n\t        set cyclA = 1\r\n\t        loop\r\n\t            exitwhen cyclA > 4\r\n\t            if udg_hero[cyclA] != null then \r\n\t                call skillst( cyclA, 1 )\r\n\t            endif\r\n\t            set cyclA = cyclA + 1\r\n\t        endloop\r\n\t    endif\r\n\t    set udg_logic[80] = true\r\n\t    call StartSound(gg_snd_QuestLog)\r\n\t    call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Human\\\\Resurrect\\\\ResurrectTarget.mdl\", GetSpellAbilityUnit(), \"origin\") )\r\n\t    call statst( GetSpellAbilityUnit(), 1, 1, 1, 0, true )\r\n\t\r\n\t    call stazisst( GetSpellAbilityUnit(), GetItemOfTypeFromUnitBJ( GetSpellAbilityUnit(), 'I0B7') )\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function OnFightEnd_Condition takes nothing returns boolean\r\n\t\treturn udg_logic[80] and not(udg_fightmod[3])\r\n\tendfunction\r\n\t\r\n\tprivate function OnFightEnd takes nothing returns nothing\r\n\t\tlocal integer i\r\n\t\r\n\t\tset udg_logic[80] = false\r\n        call IconFrameDel( \"World\" )\r\n            \r\n        set i = 1\r\n        loop\r\n            exitwhen i > 4\r\n            if udg_hero[i] != null then \r\n                call skillst( i, -1 )\r\n            endif\r\n            set i = i + 1\r\n        endloop\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    call CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n\t\tcall BattleEndGlobal.AddListener(function OnFightEnd, function OnFightEnd_Condition)\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}