{
  "Id": 50332175,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Autoload initializer init\r\n\r\n\tfunction Trig_Autoload_Conditions takes nothing returns boolean\r\n\t    return not( IsVictory ) and not(IsDefeat)\r\n\tendfunction\r\n\t\r\n\tfunction AutoloadCast takes nothing returns nothing\r\n\t    local integer id = GetHandleId( GetExpiredTimer() )\r\n\t    local integer i = LoadInteger( udg_hash, id, StringHash( \"auto\" ) )\r\n\t\r\n\t    call LoadProgress( i, \"\" )\r\n\t    call BonusLoad(i)\r\n\t    call FlushChildHashtable( udg_hash, id )\r\n\tendfunction\r\n\t\r\n\tfunction AutoLoadStart takes player user returns nothing\r\n\t\tlocal integer i = GetPlayerId(user) + 1\r\n\t    local integer id = GetHandleId( user )\r\n\t    \r\n\t    call Preloader(\"BossBattleSave\\\\Boss Battle Progress.txt\")\r\n\t    \r\n\t    if LoadTimerHandle( udg_hash, id, StringHash( \"auto\" ) ) == null  then\r\n\t        call SaveTimerHandle( udg_hash, id, StringHash( \"auto\" ), CreateTimer() )\r\n\t    endif\r\n\t\tset id = GetHandleId( LoadTimerHandle( udg_hash, id, StringHash( \"auto\" ) ) ) \r\n\t    call SaveInteger( udg_hash, id, StringHash( \"auto\" ), i )\r\n\t\tcall TimerStart( LoadTimerHandle( udg_hash, GetHandleId( user ), StringHash( \"auto\" ) ), 0.5, false, function AutoloadCast )\r\n\tendfunction\r\n\t\r\n\tfunction Trig_Autoload_Actions takes nothing returns nothing\r\n\t    call AutoLoadStart( GetTriggerPlayer() )\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    local integer cyclA = 0\r\n\t    set gg_trg_Autoload = CreateTrigger()\r\n\t    loop\r\n\t        exitwhen cyclA > 3\r\n\t        call TriggerRegisterPlayerChatEvent( gg_trg_Autoload, Player(cyclA), \"-autoload\", true )\r\n\t        set cyclA = cyclA + 1\r\n\t    endloop\r\n\t    call TriggerAddCondition( gg_trg_Autoload, Condition( function Trig_Autoload_Conditions ) )\r\n\t    call TriggerAddAction( gg_trg_Autoload, function Trig_Autoload_Actions )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}