{
  "Id": 50333500,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "globals\r\n    boolean NewbieModeDisabled = false\r\nendglobals\r\n\r\nfunction Trig_Notnew_Conditions takes nothing returns boolean\r\n    return NewbieModeDisabled == false\r\nendfunction\r\n\r\nfunction Trig_Notnew_Actions takes nothing returns nothing\r\n    local integer index = GetPlayerId( GetTriggerPlayer() ) + 1\r\n    local player user = GetTriggerPlayer()\r\n    local player playerCheck\r\n    local integer i\r\n    local boolean anyHasLevelTen = AnyHasLvL(10)\r\n\r\n    set NewbieModeDisabled = true\r\n    call DisplayTimedTextToForce( bj_FORCE_ALL_PLAYERS, 5, udg_DB_Player_Color[index] + GetPlayerName(user) + \"|r turned off beginner mode. All shops are available to you.\" )\r\n    call ShowUnit( udg_UNIT_JULE, true )\r\n    call ShowUnit( udg_UNIT_QUARTERMASTER, true )\r\n    call ShowUnit(udg_UNIT_MAGIC_TRANSFORMER, true)\r\n    \r\n    if udg_Boss_LvL == 1 then\r\n\t    set i = 0\r\n\t    loop\r\n\t    \texitwhen i >= 4\r\n\t    \tset playerCheck = Player(i)\r\n\t    \tif udg_hero[i + 1] != null and GetPlayerSlotState(playerCheck) == PLAYER_SLOT_STATE_PLAYING then\r\n\t    \t\tif playerCheck == GetLocalPlayer() then\r\n\t    \t\t\tcall BlzFrameSetVisible( modesbut, true )\r\n\t    \t\t\tif anyHasLevelTen then\r\n\t                    call BlzFrameSetVisible( modebase, true )\r\n\t                    call BlzFrameSetVisible( rotbase, true )\r\n\t                endif\r\n\t    \t\tendif\r\n\t    \tendif\r\n\t    \tset i = i + 1\r\n\t\tendloop\r\n\tendif\r\n\t\r\n\tset playerCheck = null\r\n\tset user = null\r\nendfunction\r\n\r\n/*function NptnewTip takes nothing returns nothing\r\n    local integer cyclA = 0\r\n    loop\r\n        exitwhen cyclA > 3\r\n        if udg_LvL[cyclA] <= 5 then\r\n            call DisplayTimedTextToPlayer(Player(cyclA), 0, 0, 10, \"*If you want to turn off \\\"beginner mode\\\",\")\r\n            call DisplayTimedTextToPlayer(Player(cyclA), 0, 0, 10, \"type \\\"-notnew\\\" in the chat.\")\r\n        endif\r\n        set cyclA = cyclA + 1\r\n    endloop\r\nendfunction*/\r\n\r\n//===========================================================================\r\nfunction InitTrig_Notnew takes nothing returns nothing\r\n    local integer cyclA = 0\r\n    local trigger trig = CreateTrigger()\r\n    set gg_trg_Notnew = CreateTrigger()\r\n    loop\r\n        exitwhen cyclA > 3\r\n        call TriggerRegisterPlayerChatEvent( gg_trg_Notnew, Player(cyclA), \"-notnew\", true )\r\n        set cyclA = cyclA + 1\r\n    endloop\r\n    call TriggerAddCondition( gg_trg_Notnew, Condition( function Trig_Notnew_Conditions ) )\r\n    call TriggerAddAction( gg_trg_Notnew, function Trig_Notnew_Actions )\r\n    \r\n    /*call TriggerRegisterTimerEvent(trig, 1, false)\r\n    call TriggerAddAction( trig, function NptnewTip )*/\r\n    \r\n    set trig = null\r\nendfunction",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}