{
  "Id": 50332763,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope AvengerAssemble initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant integer AMOUNT_REQUIRE = 50\r\n\tendglobals\r\n\r\n\tfunction Trig_DMCG_Conditions takes nothing returns boolean\r\n\t    return inv( udg_Event_PlayerMinionSummon_Hero, 'I095' ) > 0 and GetUnitState( udg_Event_PlayerMinionSummon_Hero, UNIT_STATE_LIFE) > 0.405 and combat( udg_Event_PlayerMinionSummon_Hero, false, 0 ) and not( udg_fightmod[3] )\r\n\tendfunction\r\n\t\r\n\tfunction Trig_DMCG_Actions takes nothing returns nothing\r\n\t    local integer i = GetPlayerId(GetOwningPlayer(udg_Event_PlayerMinionSummon_Unit)) + 1\r\n\t    local integer id = GetHandleId( udg_Event_PlayerMinionSummon_Hero )\r\n\t    local integer s = LoadInteger( udg_hash, id, StringHash( udg_QuestItemCode[4] ) ) + 1\r\n\t    \r\n\t    call SaveInteger( udg_hash, id, StringHash( udg_QuestItemCode[4] ), s )\r\n\t\r\n\t    if s >= AMOUNT_REQUIRE then\r\n\t        call RemoveItem(GetItemOfTypeFromUnitBJ(udg_Event_PlayerMinionSummon_Hero, 'I095'))\r\n\t        set bj_lastCreatedItem = CreateItem( 'I03D', GetUnitX(udg_Event_PlayerMinionSummon_Hero), GetUnitY(udg_Event_PlayerMinionSummon_Hero))\r\n\t        call UnitAddItem(udg_Event_PlayerMinionSummon_Hero, bj_lastCreatedItem)\r\n\t        call textst( \"|c00ffffff Avengers Assemble done!\", udg_Event_PlayerMinionSummon_Hero, 64, GetRandomReal( 45, 135 ), 12, 1.5 )\r\n\t        call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Human\\\\ReviveHuman\\\\ReviveHuman.mdl\", GetUnitX(udg_Event_PlayerMinionSummon_Hero), GetUnitY(udg_Event_PlayerMinionSummon_Hero) ) )\r\n\t        set udg_QuestDone[i] = true\r\n\t    else\r\n\t        call QuestDiscription( udg_Event_PlayerMinionSummon_Hero, 'I095', s, AMOUNT_REQUIRE )\r\n\t    endif\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_DMCG = CreateTrigger(  )\r\n\t    call TriggerRegisterVariableEvent( gg_trg_DMCG, \"udg_Event_PlayerMinionSummon_Real\", EQUAL, 1.00 )\r\n\t    call TriggerAddCondition( gg_trg_DMCG, Condition( function Trig_DMCG_Conditions ) )\r\n\t    call TriggerAddAction( gg_trg_DMCG, function Trig_DMCG_Actions )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}