{
  "Id": 50332778,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope IkarosQuest initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant integer ITEM_ID = 'I099'\r\n\t\tprivate constant integer REWARD_ID = 'I03H'\r\n\t\t\r\n\t\tprivate constant integer AMOUNT_REQUIRE = 2500\r\n\t\tprivate constant integer HASH_KEY = StringHash( \"ikaros_quest\" )\r\n\t\t\r\n\t\tprivate boolean QuestActive = false\r\n\t\tprivate unit QuestOwner = null\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return QuestActive and udg_fightmod[3] == false and combat( Event_AfterManaRestore_Caster, false, 0 )\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t\tlocal unit caster = QuestOwner\r\n\t    local integer i = GetPlayerId( GetOwningPlayer(caster) ) + 1\r\n\t    local integer id = GetHandleId(caster)\r\n\t    local integer p = LoadInteger( udg_hash, id, HASH_KEY ) + R2I(Event_AfterManaRestore_Amount)\r\n\t    \r\n\t    call SaveInteger( udg_hash, id, HASH_KEY, p )\r\n\t    if p >= AMOUNT_REQUIRE then\r\n\t        call SaveReal( udg_hash, id, HASH_KEY, 0 )\r\n\t        call RemoveItem(GetItemOfTypeFromUnitBJ(caster, ITEM_ID))\r\n\t        call UnitAddItem(caster, CreateItem( REWARD_ID, GetUnitX(caster), GetUnitY(caster)))\r\n\t        call textst( \"|c00ffffff Battle of Power done!\", caster, 64, GetRandomReal( 45, 135 ), 12, 1.5 )\r\n\t        call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Human\\\\ReviveHuman\\\\ReviveHuman.mdl\", GetUnitX(caster), GetUnitY(caster) ) )\r\n\t        set udg_QuestDone[i] = true\r\n\t    else\r\n\t        call QuestDiscription( caster, ITEM_ID, p, AMOUNT_REQUIRE )\r\n\t    endif\r\n\t    \r\n\t    set caster = null\r\n\tendfunction\r\n\t\r\n\tprivate function condition_pick takes nothing returns boolean\r\n\t    return GetItemTypeId(GetManipulatedItem()) == ITEM_ID\r\n\tendfunction\r\n\t\r\n\tprivate function action_pick takes nothing returns nothing\r\n\t\tset QuestActive = true\r\n\t\tset QuestOwner = GetManipulatingUnit()\r\n\tendfunction\r\n\t\r\n\tprivate function action_drop takes nothing returns nothing\r\n\t\tset QuestActive = false\r\n\t\tset QuestOwner = GetManipulatingUnit()\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_IkarosQuest = CreateTrigger(  )\r\n\t    call TriggerRegisterVariableEvent( gg_trg_IkarosQuest, \"Event_AfterManaRestore\", EQUAL, 1.00 )\r\n\t    call TriggerAddCondition( gg_trg_IkarosQuest, Condition( function condition ) )\r\n\t    call TriggerAddAction( gg_trg_IkarosQuest, function action )\r\n\t    \r\n\t    call CreateNativeEvent( EVENT_PLAYER_UNIT_PICKUP_ITEM, function action_pick, function condition_pick )\r\n\t    call CreateNativeEvent( EVENT_PLAYER_UNIT_DROP_ITEM, function action_drop, function condition_pick )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}