{
  "Id": 50332769,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Sandro initializer init \r\n\r\n\tglobals\r\n\t\tprivate constant integer SANDRO_CHARGES = 10\r\n\tendglobals\r\n\r\n\tprivate function Sandro takes unit caster, item itm returns nothing\r\n\t\tlocal integer cyclA = 2\r\n\t\tlocal integer array it\r\n\t\tlocal integer k = LoadInteger( udg_hash, GetHandleId(itm), StringHash( \"snddk\" ) )\r\n\t\tlocal boolean l\r\n\t\tlocal string text\r\n\t\r\n\t    //Нельзя иметь [-1] в локали\r\n\t\tset it[0] = 0\r\n\t\tset it[1] = 0\r\n\t\tloop\r\n\t\t\texitwhen cyclA > 4\r\n\t\t\tset it[cyclA] = DB_Items[2][GetRandomInt( 1, udg_Database_NumberItems[2] )]\r\n\t\t\tif (it[cyclA] == it[cyclA-1] or it[cyclA] == it[cyclA-2]) and udg_Database_NumberItems[2] > 2 then\r\n\t\t\t\tset cyclA = cyclA - 1\r\n\t\t\tendif\r\n\t\t\tset cyclA = cyclA + 1\r\n\t\tendloop\r\n\t\r\n\t\tset text = words( caster, BlzGetItemDescription(itm), \"|cffffffff\", \"|r\", I2S( SANDRO_CHARGES - k ) )\r\n\t    call BlzSetItemExtendedTooltip( itm, text )\r\n\t\tset l = k >= SANDRO_CHARGES - 1\r\n\t\r\n\t\tcall forge( caster, itm, it[2], it[3], it[4], l )\r\n\t    \r\n\t    set caster = null\r\n\t    set itm = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function OnAfterForge_Condition takes nothing returns boolean\r\n\t    return Event_AfterForge_ForgedItem == 'I03F' and Event_AfterForge_ForgedItem_Item != null\r\n\tendfunction\r\n\t\r\n\tprivate function OnAfterForge takes nothing returns nothing\r\n\t\tlocal integer id = GetHandleId(Event_AfterForge_ForgedItem_Item)\r\n\t\tlocal integer counter = LoadInteger( udg_hash, id, StringHash( \"snddk\" ) ) + 1\r\n\t\tcall SaveInteger( udg_hash, id, StringHash( \"snddk\" ), counter )\r\n\t    call Sandro( Event_AfterForge_Hero, Event_AfterForge_ForgedItem_Item )\r\n\tendfunction\r\n\r\n\t//===========================================================================\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetItemTypeId(GetManipulatedItem()) == 'I03F'\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    call Sandro( GetManipulatingUnit(), GetManipulatedItem() )\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t\tcall CreateNativeEvent( EVENT_PLAYER_UNIT_USE_ITEM, function action, function condition )\r\n\t    call CreateEventTrigger( \"Event_AfterForge_Real\", function OnAfterForge, function OnAfterForge_Condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}