{
  "Id": 50332761,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope ScolarGambit initializer init\r\n\r\n\tglobals\r\n\t\tprivate constant integer AMOUNT_REQUIRE = 25\r\n\tendglobals\r\n\r\n\tfunction Trig_SLCG_Conditions takes nothing returns boolean\r\n\t    return GetUnitTypeId(GetSellingUnit()) == 'h007' and inv( GetBuyingUnit(), 'I0B9' ) > 0\r\n\tendfunction\r\n\t\r\n\tfunction Trig_SLCG_Actions takes nothing returns nothing\r\n\t    local integer i = GetPlayerId(GetOwningPlayer(GetBuyingUnit())) + 1\r\n\t    local integer id = GetHandleId( GetBuyingUnit() )\r\n\t    local integer s = LoadInteger( udg_hash, id, StringHash( udg_QuestItemCode[16] ) ) + 1\r\n\t    \r\n\t    call SaveInteger( udg_hash, id, StringHash( udg_QuestItemCode[16] ), s )\r\n\t\r\n\t    if s >= AMOUNT_REQUIRE then\r\n\t        call RemoveItem( GetItemOfTypeFromUnitBJ(GetBuyingUnit(), 'I0B9') )\r\n\t        call UnitAddItem(GetBuyingUnit(), CreateItem( 'I0EZ', GetUnitX(GetBuyingUnit()), GetUnitY(GetBuyingUnit())))\r\n\t        call textst( \"|c00ffffff Scholar's Gambit done!\", GetBuyingUnit(), 64, GetRandomReal( 45, 135 ), 12, 1.5 )\r\n\t        call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Human\\\\ReviveHuman\\\\ReviveHuman.mdl\", GetUnitX(GetBuyingUnit()), GetUnitY(GetBuyingUnit()) ) )\r\n\t        set udg_QuestDone[i] = true\r\n\t    else\r\n\t        call QuestDiscription( GetBuyingUnit(), 'I0B9', s, AMOUNT_REQUIRE )\r\n\t    endif\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_SLCG = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( gg_trg_SLCG, EVENT_PLAYER_UNIT_SELL_ITEM )\r\n\t    call TriggerAddCondition( gg_trg_SLCG, Condition( function Trig_SLCG_Conditions ) )\r\n\t    call TriggerAddAction( gg_trg_SLCG, function Trig_SLCG_Actions )\r\n\tendfunction\r\n\r\nendscope\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}