{
  "Id": 50332765,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope SPIG initializer init\r\n\t\r\n\tfunction Trig_SPIG_Conditions takes nothing returns boolean\r\n\t    return inv( GetDyingUnit(), 'I097' ) > 0 and combat( GetDyingUnit(), false, 0 ) and not( udg_fightmod[3] )\r\n\tendfunction\r\n\t\r\n\tfunction Trig_SPIG_Actions takes nothing returns nothing\r\n\t    local integer i = GetUnitUserData(GetDyingUnit())\r\n\t    local integer id = GetHandleId( GetDyingUnit() )\r\n\t    local integer s = LoadInteger( udg_hash, id, StringHash( udg_QuestItemCode[5] ) ) + 1\r\n\t    local item it = GetItemOfTypeFromUnitBJ(GetDyingUnit(), 'I097')\r\n\t    \r\n\t    call SaveInteger( udg_hash, id, StringHash( udg_QuestItemCode[5] ), s )\r\n\t\r\n\t    if s == udg_QuestNum[5] then\r\n\t        call BlzSetItemExtendedTooltip( it, words( GetDyingUnit(), BlzGetItemDescription(it), \"|cFF959697(\", \")|r\", \"Complete!\" ) ) // sadtwig\r\n\t        //call BlzSetItemIconPath( it, words( GetDyingUnit(), BlzGetItemDescription(it), \"|cFF959697(\", \")|r\", \"Complete!\" ) )\r\n\t    elseif s < udg_QuestNum[5] then\r\n\t        call QuestDiscription( GetDyingUnit(), 'I097', s, udg_QuestNum[5] )\r\n\t    endif\r\n\t    \r\n\t    set it = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function OnBattleEnd_Condition takes nothing returns boolean\r\n\t\treturn LoadInteger( udg_hash, GetHandleId( BattleEnd.TriggerUnit ), StringHash( \"spig\" ) ) >= 5 and inv( BattleEnd.TriggerUnit, 'I097' ) > 0\r\n\tendfunction\r\n\t\r\n\tprivate function OnBattleEnd takes nothing returns nothing\r\n\t\tlocal unit hero = BattleEnd.GetDataUnit(\"caster\")\r\n\t\t\r\n\t\tcall RemoveItem( GetItemOfTypeFromUnitBJ(hero, 'I097') )\r\n        set bj_lastCreatedItem = CreateItem( 'I03F', GetUnitX(hero), GetUnitY(hero))\r\n        call UnitAddItem(hero, bj_lastCreatedItem)\r\n        call textst( \"|c00ffffff Total Destruction done!\", hero, 64, GetRandomReal( 45, 135 ), 12, 1.5 )\r\n        call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Human\\\\ReviveHuman\\\\ReviveHuman.mdl\", GetUnitX(hero), GetUnitY(hero) ) )\r\n        set udg_QuestDone[GetPlayerId( GetOwningPlayer(hero) ) + 1] = true  \r\n\t\t\r\n\t\tset hero = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    set gg_trg_SPIG = CreateTrigger(  )\r\n\t    call TriggerRegisterAnyUnitEventBJ( gg_trg_SPIG, EVENT_PLAYER_UNIT_DEATH )\r\n\t    call TriggerAddCondition( gg_trg_SPIG, Condition( function Trig_SPIG_Conditions ) )\r\n\t    call TriggerAddAction( gg_trg_SPIG, function Trig_SPIG_Actions )\r\n\t    \r\n\t    call BattleEnd.AddListener(function OnBattleEnd, function OnBattleEnd_Condition)\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}