{
  "Id": 50332781,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope BattlemasterBulwark initializer init\r\n\r\n    globals\r\n        private constant integer ABILITY_ID = 'A1IH'\r\n        private constant integer EFFECT_ID = 'A1IJ'\r\n        private constant integer BUFF_ID = 'B0B4'\r\n        private constant integer INVUL_ID = 'A1IK'\r\n        private constant integer DURATION = 10\r\n    endglobals\r\n    \r\n    private function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_ID\r\n\tendfunction\r\n\r\n    private function action takes nothing returns nothing\r\n        local unit caster \r\n\t\tlocal unit target \r\n\t\tlocal real t\r\n\t\t\r\n\t\tif CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = udg_Target\r\n\t        set t = udg_Time\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = randomtarget( caster, 900, \"ally\", RT_NOT_CASTER, RT_HERO, 0 )\r\n\t        call textst( udg_string[0] + GetObjectName('A12B'), caster, 64, 90, 10, 1.5 )\r\n\t        set t = 10\r\n\t        if target == null then\r\n\t            set caster = null\r\n\t            return\r\n\t        endif\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set target = GetSpellTargetUnit()\r\n\t        set t = 10\r\n\t    endif\r\n\t    set t = timebonus(caster, t)\r\n        \r\n        call bufallst( caster, target, EFFECT_ID, INVUL_ID, 0, 0, 0, BUFF_ID, \"bulwark\", DURATION )\r\n        \r\n        set caster = null\r\n        set target = null\r\n    endfunction\r\n\r\n    //===========================================================================\r\n    private function init takes nothing returns nothing\r\n        call CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n    endfunction\r\n\r\nendscope\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}