{
  "Id": 50332919,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope HungryLeech initializer init\r\n\r\n    globals\r\n        private constant integer ID_ITEM = 'I0DG'\r\n        private constant real PERCENT_AMOUNT = 0.6\r\n        private boolean isLoop = false\r\n    endglobals\r\n\r\n\t//===========================================================================\r\n    private function AfterHealEvent_Conditions takes nothing returns boolean\r\n        return IsHeroHasItem( Event_AfterHeal_Target, ID_ITEM ) and Event_AfterHeal_Target != Event_AfterHeal_Caster and isLoop == false\r\n    endfunction\r\n    \r\n    private function AfterHealEvent takes nothing returns nothing\r\n        set isLoop = true\r\n        call healst( Event_AfterHeal_Target, Event_AfterHeal_Caster, Event_AfterHeal_Heal * PERCENT_AMOUNT )\r\n        set isLoop = false\r\n    endfunction\r\n    \r\n    //===========================================================================\r\n    private function AfterManaRestoreEvent_Conditions takes nothing returns boolean\r\n        return IsHeroHasItem( Event_AfterManaRestore_Target, ID_ITEM ) and Event_AfterManaRestore_Target != Event_AfterManaRestore_Caster and isLoop == false\r\n    endfunction\r\n    \r\n    private function AfterManaRestoreEvent takes nothing returns nothing\r\n        set isLoop = true\r\n        call manast( Event_AfterManaRestore_Target, Event_AfterManaRestore_Caster, Event_AfterManaRestore_Amount * PERCENT_AMOUNT )\r\n        set isLoop = false\r\n    endfunction\r\n\r\n    //===========================================================================\r\n    private function init takes nothing returns nothing\r\n        call CreateEventTrigger(\"Event_AfterHeal_Real\", function AfterHealEvent, function AfterHealEvent_Conditions )\r\n        call CreateEventTrigger(\"Event_AfterManaRestore\", function AfterManaRestoreEvent, function AfterManaRestoreEvent_Conditions )\r\n    endfunction\r\n    \r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}