{
  "Id": 50332727,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope PharaohRing initializer init\r\n\t\r\n\tglobals\r\n\t\tprivate constant integer ABILITY_ID = 'A13X'\r\n\t\tprivate constant integer DAMAGE = 250\r\n\t\tprivate constant real DURATION = 1.5\r\n\t\tprivate constant integer MULTIPLIER = 3\r\n\t\tprivate constant string ANIMATION = \"Abilities\\\\Spells\\\\Other\\\\Incinerate\\\\FireLordDeathExplode.mdl\"\r\n\tendglobals\r\n\t\r\n\tprivate function condition takes nothing returns boolean\r\n\t    return GetSpellAbilityId() == ABILITY_ID\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local integer i\r\n\t    local integer iMax\r\n\t    local unit caster\r\n\t    local unit target\r\n\t    local real duration\r\n\t    local integer damage\r\n\t    \r\n\t    if CastLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = udg_Target\r\n\t    elseif RandomLogic() then\r\n\t        set caster = udg_Caster\r\n\t        set target = randomtarget( caster, 900, \"enemy\", 0, 0, 0 )\r\n\t        call textst( udg_string[0] + GetObjectName(ABILITY_ID), caster, 64, 90, 10, 1.5 )\r\n\t        if target == null then\r\n\t            set caster = null\r\n\t            return\r\n\t        endif\r\n\t    else\r\n\t        set caster = GetSpellAbilityUnit()\r\n\t        set target = GetSpellTargetUnit()\r\n\t    endif\r\n\t    \r\n\t    set damage = DAMAGE\r\n\t    set duration = DURATION\r\n\t\r\n\t    if LoadBoolean( udg_hash, GetHandleId( caster ), StringHash( \"unique\" ) ) then\r\n\t        set damage = damage * MULTIPLIER\r\n\t    \tset duration = duration * MULTIPLIER\r\n\t    endif\r\n\t\r\n\t    call DestroyEffect( AddSpecialEffectTarget( ANIMATION, target, \"origin\" ) )\r\n\t    set i = 1\r\n\t    set iMax = eyest( caster )\r\n\t    loop\r\n\t        exitwhen i > iMax\r\n\t        call UnitDamageTarget( caster, target, damage, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n\t        call UnitStun(caster, target, duration )\r\n\t        set i = i + 1\r\n\t    endloop\r\n\t    \r\n\t    set caster = null\r\n\t    set target = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t    call CreateNativeEvent( EVENT_PLAYER_UNIT_SPELL_EFFECT, function action, function condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}