{
  "Id": 50332344,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope SlippersOfMadness initializer init\r\n    \r\n    globals\r\n        private constant integer ITEM_ID = 'I01L'\r\n        \r\n        private constant integer STAT_TO_ADD = 2\r\n    endglobals\r\n    \r\n    private struct ItemStat\r\n    \treadonly string color\r\n\t\treadonly string name\r\n\t\treadonly integer direction\r\n\t\treadonly integer save_code\r\n\t\t\r\n\t\tstatic method create takes string color, string name, integer direction, integer save_code returns thistype\r\n\t\t\tlocal thistype p = thistype.allocate()\r\n\t\t\t\r\n\t\t\tset p.color = color\r\n\t\t\tset p.name = name\r\n\t\t\tset p.direction = direction\r\n\t\t\tset p.save_code = save_code\r\n\t\t\t\r\n            return p\r\n        endmethod\r\n    \r\n    endstruct\r\n    \r\n    globals\r\n    \tprivate ItemStat array SlippersStat[3]\r\n    endglobals\r\n    \r\n    private function condition takes nothing returns boolean\r\n        return udg_fightmod[3] == false\r\n    endfunction\r\n\r\n    private function action takes nothing returns nothing\r\n        local unit hero = BattleEnd.GetDataUnit(\"caster\")\r\n        local integer i\r\n          \r\n        call statst( hero, STAT_TO_ADD, 0, 0, SlippersStat[0].save_code, true )\r\n        call statst( hero, 0, STAT_TO_ADD, 0, SlippersStat[1].save_code, true )\r\n        call statst( hero, 0, 0, STAT_TO_ADD, SlippersStat[2].save_code, true )\r\n        set i = 0\r\n        loop\r\n            exitwhen i > 2\r\n            call textst( SlippersStat[i].color + \"+\" + I2S(STAT_TO_ADD) + \" \" + SlippersStat[i].name, hero, 64, SlippersStat[i].direction, 8, 2.5 )\r\n        \tset i = i + 1\r\n        endloop\r\n        \r\n        set hero = null\r\n    endfunction\r\n\r\n\t//===========================================================================\r\n\tprivate function Creation takes nothing returns nothing\r\n\t\tset SlippersStat[0] = ItemStat.create(\"|c00FF2020\", \"strength\", 30, 68)\r\n\t\tset SlippersStat[1] = ItemStat.create(\"|c0020FF20\", \"agility\", 150, 72)\r\n\t\tset SlippersStat[2] = ItemStat.create(\"|c002020FF\", \"intelligence\", 270, 76)\r\n\tendfunction\r\n\t\r\n    //===========================================================================\r\n    private function init takes nothing returns nothing\r\n        local trigger trig = CreateTrigger()\r\n\t    call TriggerRegisterTimerEvent( trig, 0.04, false)\r\n\t    call TriggerAddAction( trig, function Creation )\r\n\t    \r\n\t    call RegisterDuplicatableItemTypeCustom( ITEM_ID, BattleEnd, function action, function condition, null )\r\n        \r\n        set trig = null\r\n    endfunction\r\n    \r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}